### ISSUE TITLE
[Java][Files] False positive in CreateFileSinkModels 

### ISSUE THREAD

**Issue by chmodxxx** [github/codeql#11309]
**The class CreateFileSinkModels defines `createTempDirectory` as  sink, however this doesn't seem to be  vulnerable* , not sure if it's a java version thing or it's actually not a vulnerable sink.

Example code that errors out

```
import java.nio.file.Files;
import java.nio.file.Path;


public class test {

	public static void main(String[] args)
	{
		try {
			Path tempDir = Files.createTempDirectory("foobar-" + "/../../tmp/foo");
			System.out.println(
				"Temporary Directory created at:\n"
				+ tempDir.toString());
		}
		catch (Exception e) {
			e.printStackTrace();
		}
	}
}


```

Error => 
```
java.lang.IllegalArgumentException: Invalid prefix or suffix
	at java.base/java.nio.file.TempFileHelper.generatePath(TempFileHelper.java:62)
	at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:126)
	at java.base/java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:172)
	at java.base/java.nio.file.Files.createTempDirectory(Files.java:1011)
	at test.main(test.java:10)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:415)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:192)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:132)

```

https://github.com/github/codeql/blob/5b67ba2939865cef38f07f1ba1393a2920e20a25/java/ql/lib/semmle/code/java/security/Files.qll#L31

**Comment by aeisenberg** [comment]
Hi, thanks for reporting this false positive. Can you please further clarify what the problem is? Are you saying that `createTempDirectory` should not be identified as a sink? I believe this is incorrect. If user controlled data, unsanitized data can be passed to this function, then a bad actor can create a temp directory with an unexpected name. This in itself is not enough to gain access to the system, but it would be part of a larger way to attack.

Please let me know if I have misunderstood.

**Comment by chmodxxx** [comment]
Thanks @aeisenberg  , for some reason the alerted sounded like a path traversal flag, hence I thought this shouldn't be vulnerable to traversal, but I see your argument. 
Closing.
