### ISSUE TITLE
Could not find qlpack file for dbscheme semmlecode.dbscheme (codeQL.viewAstContextExplorer)

### ISSUE THREAD

**Issue by abc767234318** [github/codeql#13505]
**Description of the issue**
I can't view the AST when I use the "CodeQL for Visual Studio Code" extension.

### Steps to reproduce
```
git clone https://github.com/xuxueli/xxl-job.git
cd xxl-job
codeql database create xxljob --language=java --command="mvn clean install"
```
And then:
<img width="435" alt="image" src="https://github.com/github/codeql/assets/51507451/c8b8045f-7e69-420a-aa8d-1ed18d12300a">

I check the CodeQL Extension log:
```
Could not find qlpack file for dbscheme semmlecode.dbscheme (codeQL.viewAstContextExplorer)
Error: Could not find qlpack file for dbscheme semmlecode.dbscheme
    at findDbschemePack (/Users/ping/.vscode/extensions/github.vscode-codeql-1.8.6/out/extension.js:142625:9)
    at getQlPackForDbscheme (/Users/ping/.vscode/extensions/github.vscode-codeql-1.8.6/out/extension.js:142658:24)
    at qlpackOfDatabase (/Users/ping/.vscode/extensions/github.vscode-codeql-1.8.6/out/extension.js:142692:10)
    at TemplatePrintAstProvider.getAst (/Users/ping/.vscode/extensions/github.vscode-codeql-1.8.6/out/extension.js:143089:21)
    at CachedOperation.get (/Users/ping/.vscode/extensions/github.vscode-codeql-1.8.6/out/extension.js:142934:22)
    at TemplatePrintAstProvider.provideAst (/Users/ping/.vscode/extensions/github.vscode-codeql-1.8.6/out/extension.js:143063:52)
    at withProgress.cancellable (/Users/ping/.vscode/extensions/github.vscode-codeql-1.8.6/out/extension.js:159396:19)
```

**Comment by aibaars** [comment]
Is the `codeql/java-all` QL pack available in your vscode? I think having https://github.com/github/codeql in the vscode workspace should work.
