### ISSUE TITLE
The TypeScript parser wrapper crashed with exit code 1

### ISSUE THREAD

**Issue by eustas** [github/codeql#13656]
**Description of the issue**

https://github.com/google/brotli/actions/runs/5452208622/jobs/9919406550

```
  [2023-07-04 07:57:15] [build-stdout] Extracting /home/runner/work/brotli/brotli/js/test_data.ts
  [2023-07-04 07:57:48] [build-stderr] /opt/hostedtoolcache/CodeQL/2.13.4/x64/codeql/javascript/tools/typescript-parser-wrapper/main.js:250
  [2023-07-04 07:57:48] [build-stderr]     return JSON.stringify(obj, function (k, v) {
  [2023-07-04 07:57:48] [build-stderr]                 ^
  [2023-07-04 07:57:48] [build-stderr] RangeError: Invalid string length
  [2023-07-04 07:57:48] [build-stderr]     at JSON.stringify (<anonymous>)
  [2023-07-04 07:57:48] [build-stderr]     at stringifyAST (/opt/hostedtoolcache/CodeQL/2.13.4/x64/codeql/javascript/tools/typescript-parser-wrapper/main.js:250:17)
  [2023-07-04 07:57:48] [build-stderr]     at extractFile (/opt/hostedtoolcache/CodeQL/2.13.4/x64/codeql/javascript/tools/typescript-parser-wrapper/main.js:256:12)
  [2023-07-04 07:57:48] [build-stderr]     at prepareNextFile (/opt/hostedtoolcache/CodeQL/2.13.4/x64/codeql/javascript/tools/typescript-parser-wrapper/main.js:267:33)
  [2023-07-04 07:57:48] [build-stderr]     at /opt/hostedtoolcache/CodeQL/2.13.4/x64/codeql/javascript/tools/typescript-parser-wrapper/main.js:281:9
  [2023-07-04 07:57:48] [build-stderr]     at afterWrite (node:internal/streams/writable:500:5)
  [2023-07-04 07:57:48] [build-stderr]     at afterWriteTick (node:internal/streams/writable:487:10)
  [2023-07-04 07:57:48] [build-stderr]     at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
  [2023-07-04 07:57:48] [build-stderr] Node.js v18.16.1
  [2023-07-04 07:57:48] [build-stderr] Exception while extracting /home/runner/work/brotli/brotli/js/test_data.ts.
  [2023-07-04 07:57:48] [build-stderr] com.semmle.util.exception.CatastrophicError: The TypeScript parser wrapper crashed with exit code 1
  [2023-07-04 07:57:48] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.getExceptionFromMalformedResponse(TypeScriptParser.java:416)
  [2023-07-04 07:57:48] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.talkToParserWrapper(TypeScriptParser.java:381)
  [2023-07-04 07:57:48] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.parse(TypeScriptParser.java:451)
  [2023-07-04 07:57:48] [build-stderr] 	at com.semmle.js.extractor.TypeScriptExtractor.extract(TypeScriptExtractor.java:24)
  [2023-07-04 07:57:48] [build-stderr] 	at com.semmle.js.extractor.FileExtractor.extractContents(FileExtractor.java:547)
  [2023-07-04 07:57:48] [build-stderr] 	at com.semmle.js.extractor.FileExtractor.extract(FileExtractor.java:454)
  [2023-07-04 07:57:48] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.doExtract(AutoBuild.java:1235)
  [2023-07-04 07:57:48] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.extract(AutoBuild.java:1221)
  [2023-07-04 07:57:48] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.extractTypeScriptFiles(AutoBuild.java:1174)
  [2023-07-04 07:57:48] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.extractTypeScript(AutoBuild.java:1071)
  [2023-07-04 07:57:48] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.extractSource(AutoBuild.java:753)
  [2023-07-04 07:57:48] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.run(AutoBuild.java:[46](https://github.com/google/brotli/actions/runs/5452208622/jobs/9919406550#step:8:47)0)
  [2023-07-04 07:57:[48](https://github.com/google/brotli/actions/runs/5452208622/jobs/9919406550#step:8:49)] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.main(AutoBuild.java:1340)
  Error: 7-04 07:57:[49](https://github.com/google/brotli/actions/runs/5452208622/jobs/9919406550#step:8:50)] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/2.13.4/x[64](https://github.com/google/brotli/actions/runs/5452208622/jobs/9919406550#step:8:65)/codeql/javascript/tools/autobuild.sh])
  A fatal error occurred: Exit status 1 from command: [/opt/hostedtoolcache/CodeQL/2.13.4/x64/codeql/javascript/tools/autobuild.sh]
  Error: A fatal error occurred.
```

**Comment by smowton** [comment]
The root of the issue is that `test_data.ts` file being enormous. In the short term you can exclude it from analysis, by creating a CodeQL configuration file (https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/customizing-code-scanning#using-a-custom-configuration-file) and excluding that file (https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/customizing-code-scanning#specifying-directories-to-scan)

Meanwhile I'll raise the general issue of dealing with this situation more generally with the team.

**Comment by erik-krogh** [comment]
The issue should be fixed with https://github.com/github/codeql/pull/16546.  

It'll take some weeks before that PR lands in a new release.
