### ISSUE TITLE
Failed to create database on Android

### ISSUE THREAD

**Issue by SureBelong** [github/codeql#14404]
Hi

1. I'm trying to run CodeQL on Android with this command:

codeql database create --language="java" --source-root=frameworks/base/services --command="`pwd`/build/soong/soong_ui.bash --make-mode -j32 services" -v --overwrite -M 4096 --no-cleanup -- codeql-database/services-database

2. But I'm getting this error while building:

```
FAILED: //external/auto/service:auto_service_annotations javac [linux_glibc common]
Outputs: out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/auto_service_annotations.jar
Error: exited with code: 1
Command: rm -rf "out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/classes" "out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/anno" "out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/srcjars" "out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/auto_service_annotations.jar" && mkdir -p "out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/classes" "out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/anno" "out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/srcjars" && out/host/linux-x86/bin/zipsync -d out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/srcjars -l out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/srcjars/list -f "*.java"  && (if [ -s out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/srcjars/list ] || [ -s out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/auto_service_annotations.jar.rsp ] ; then out/host/linux-x86/bin/soong_javac_wrapper prebuilts/jdk/jdk17/linux-x86/bin/javac -J-Xmx4096M -J-XX:OnError="cat hs_err_pid%p.log" -J-XX:CICompilerCount=6 -J-XX:+UseDynamicNumberOfGCThreads -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath "" -g -XDskipDuplicateBridges=true -XDstringConcat=inline  -proc:none -Xlint:-dep-ann   -source 17 -target 17 -d out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/classes -s out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/anno @out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/auto_service_annotations.jar.rsp @out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/srcjars/list ; fi ) && out/host/linux-x86/bin/soong_zip -jar -o out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/auto_service_annotations.jar -C out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/classes -D out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/classes && rm -rf "out/soong/.intermediates/external/auto/service/auto_service_annotations/linux_glibc_common/javac/srcjars"
Output:
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "arg" is null
	at com.semmle.extractor.java.args.JavaExtractorArgs.parse(JavaExtractorArgs.java:57)
	at com.semmle.extractor.java.JavaExtractor.<init>(JavaExtractor.java:200)
	at com.semmle.extractor.java.JavaExtractor.main(JavaExtractor.java:512)
[Process Builder] Spawned process exited abnormally (code 1; tried to run: [/home2/user1/AOSP/prebuilts/jdk/jdk17/linux-x86/bin/java, -Dfile.encoding=UTF-8, -Xmx1024M, -Xms256M, --add-opens, java.base/sun.reflect.annotation=ALL-UNNAMED, -Xmx4096M, -Xms256M, -classpath, /home2/user1/AOSP/vendor/111/external/ScanningTools/codeql/engine/java/tools/semmle-extractor-java.jar:/home2/user1/AOSP/vendor/111/external/ScanningTools/codeql/engine/java/tools/lombok-javac-extend.jar, com.semmle.extractor.java.JavaExtractor, --jdk-version, 17, --javac-args, @@@/home2/user1/AOSP/codeql-database/sensitive_info_log/services-database/log/ext/javac-3.args]
[ODASA Javac] Non-zero exit code 1 from ODASA javac builder
Exception in thread "main" java.lang.Error: Fatal extractor error detected. Attempting to abort build commands.
	at com.semmle.extractor.java.interceptors.JavacMainInterceptor.javacMainResult(JavacMainInterceptor.java:53)
	at jdk.compiler/com.sun.tools.javac.main.Main.SEMMLE_INTERCEPT$9(Main.java)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:329)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

3. In addition, we can successfully create database using the same command on Android13. 
We are using the latest release of codeql:https://github.com/github/codeql-cli-binaries/releases/tag/v2.14.6

Please help to check the reasons for the above errors, thank you.

**Comment by smowton** [comment]
Could you clarify what repository you're building, and what ref you had checked out when you ran the `database create` command you give above?

**Comment by SureBelong** [comment]
We created a database for platform/frameworks/base of Android14.

Sorry, we have not yet analyzed the direction of this issue.

**Comment by smowton** [comment]
Could you clarify what repository you mean by Android14? There are a few different repositories with `frameworks/base/services` in them.

**Comment by SureBelong** [comment]
The Repository name is platform/frameworks/base.
The module name is services, and it is in directory frameworks/base. When we compile this module, we execute the "make service" command in the root directory

**Comment by smowton** [comment]
Could you please tell me how to reproduce the error, starting from a fresh image?

For example, what repositories do you need to check out, what specific commit of those repositories are you using, what dependencies do you need to install, and what steps do you need to take before running `soong_ui.bash`?

An ideal way to do this would be to reproduce the failure in an Actions environment and give a link to the failing Actions run, but a list of commands to reproduce the failure starting from a clean environment would also be fine.

**Comment by smowton** [comment]
For example, I found https://android.googlesource.com/platform/frameworks/base.git, and the fact that you ran `soong_ui.bash` suggests I probably also need https://android.googlesource.com/platform/build/soong ? And you mentioned Android 14, so perhaps I should check out tag `android-14.0.0_r11` of both repositories?

But `soong_ui.bash` can't just be run straight off, there are clearly preparatory steps needed first... but I'm having to guess a lot, so it is unlikely I will reproduce your circumstances properly. If you could specify exactly what steps you took, it will be much easier to reproduce and debug the failure you're seeing.

**Comment by SureBelong** [comment]
We are not able to tell exactly which repositories the "services" module depends on, because this issue occurred when we created the database of the “services” module after downloading all the code repositories of Android14.

Our steps are as follows,
1.Download Android14's all code repository
2.Put the code for the codeql tool in the codeql directory
3.Run the". ql-prepare.sh" command. The code in the script is as follows,
`#!/bin/bash
set -ex

mkdir -p codeql-database

source build/envsetup.sh

export ALLOW_NINJA_ENV=true
export SEMMLE_JAVA_EXTRACTOR_JVM_ARGS="-Xmx4096M -Xms256M"

codeql/codeql database create --language="java" --source-root=frameworks/base/services --command="`pwd`/build/soong/soong_ui.bash --make-mode -j32 services" -v --overwrite -M 4096 --no-cleanup -- codeql-database/services-database`

Can you help to reproduce this issue on the premise of downloading all the code repositories for Android14?

**Comment by SureBelong** [comment]
We are not able to tell exactly which repositories the "services" module depends on, because this issue occurred when we created the database of the “services” module after downloading all the code repositories of Android14.

Our steps are as follows,
1.Download Android14's all code repository
2.Put the code for the codeql tool in the codeql directory
3.Run the". ql-prepare.sh" command. The code in the script is as follows,
`#!/bin/bash
set -ex

mkdir -p codeql-database

source build/envsetup.sh

export ALLOW_NINJA_ENV=true
export SEMMLE_JAVA_EXTRACTOR_JVM_ARGS="-Xmx4096M -Xms256M"

codeql/codeql database create --language="java" --source-root=frameworks/base/services --command="`pwd`/build/soong/soong_ui.bash --make-mode -j32 services" -v --overwrite -M 4096 --no-cleanup -- codeql-database/services-database`

Can you help to reproduce this issue on the premise of downloading all the code repositories for Android14?
