### ISSUE TITLE
"Could not start Node.js" issue when building database with cluster-db option

### ISSUE THREAD

**Issue by st1ckyf1ng4z** [github/codeql#15970]
When i try to build database for multi-language repo with command like this:

`database create -l go,javascript --no-run-unnecessary-builds --source-root . --db-cluster test_codeql_dbs -v`

every time receive an error for Node.js:

```
Running command in /tmp/test: [/home/codeql/codeql/javascript/tools/autobuild.sh]
[2024-03-19 11:25:54] [build-stdout] Single-threaded extraction.
[2024-03-19 11:26:09] [build-stdout] ui/apps/platform/package.json: Main file set to ui/apps/platform/src/index.tsx
[2024-03-19 11:26:09] [build-stdout] ui/packages/tailwind-config/package.json: Main file set to ui/packages/tailwind-config/tailwind.config.js
[2024-03-19 11:26:09] [build-stdout] ui/packages/ui-components/package.json: Main file set to ui/packages/ui-components/src/index.ts
[2024-03-19 11:26:09] [build-stdout] tests/performance/package.json: Main file not found
[2024-03-19 11:26:09] [build-stdout] ui/package.json: Main file not found
[2024-03-19 11:26:12] [build-stdout] Extracting /tmp/test/ui/apps/platform/public/index.html
[2024-03-19 11:26:12] [build-stdout] Done extracting /tmp/test/ui/apps/platform/public/index.html (80 ms)
[2024-03-19 11:26:12] [build-stdout] Extracting /tmp/test/utils/login/authorize.html
[2024-03-19 11:26:12] [build-stdout] Done extracting /tmp/test/utils/login/authorize.html (14 ms)
[2024-03-19 11:26:13] [build-stderr] Could not start Node.js. It is required for TypeScript extraction.
[2024-03-19 11:26:13] [build-stderr] Please install Node.js and ensure 'node' is on the PATH.
[2024-03-19 11:26:13] [build-stderr] at com.semmle.ts.extractor.TypeScriptParser.startNodeAndGetVersion(TypeScriptParser.java:256)
[2024-03-19 11:26:13] [build-stderr] at com.semmle.ts.extractor.TypeScriptParser.verifyNodeInstallation(TypeScriptParser.java:217)
[2024-03-19 11:26:13] [build-stderr] at com.semmle.ts.extractor.TypeScriptParser.verifyInstallation(TypeScriptParser.java:178)
[2024-03-19 11:26:13] [build-stderr] at com.semmle.js.extractor.AutoBuild.verifyTypeScriptInstallation(AutoBuild.java:1167)
[2024-03-19 11:26:13] [build-stderr] at com.semmle.js.extractor.AutoBuild.extractTypeScript(AutoBuild.java:1021)
[2024-03-19 11:26:13] [build-stderr] at com.semmle.js.extractor.AutoBuild.extractSource(AutoBuild.java:755)
[2024-03-19 11:26:13] [build-stderr] at com.semmle.js.extractor.AutoBuild.run(AutoBuild.java:462)
[2024-03-19 11:26:13] [build-stderr] at com.semmle.js.extractor.AutoBuild.main(AutoBuild.java:1352)
[2024-03-19 11:26:13] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/home/codeql/codeql/tools/linux64/preload_tracer, /home/codeql/codeql/javascript/tools/autobuild.sh])
A fatal error occurred: Exit status 1 from command: [/home/codeql/codeql/javascript/tools/autobuild.sh]
```

But when i run database create command directly for javascript - where are not any errors, database created successfully.

`codeql database create -l javascript --no-run-unnecessary-builds --source-root . test_codeql_javascript_db -v`

```
Writing logs to /tmp/test/test_codeql_javascript_db/log/database-create-20240319.113715.452.log.
Initializing database at /tmp/test/test_codeql_javascript_db.
Calculating baseline information in /tmp/test
Running command in /tmp/test: [/home/codeql/codeql/go/tools/configure-baseline.sh]
Running command in /tmp/test: [/home/codeql/codeql/javascript/tools/configure-baseline.sh]
Calculated baseline information for languages: go, java, javascript, python (1.9s).
Resolving extractor javascript.
Successfully loaded extractor JavaScript/TypeScript (javascript) from /home/codeql/codeql/javascript.
Created skeleton CodeQL database at /tmp/test/test_codeql_javascript_db. This in-progress database is ready to be populated by an extractor.
Running build command: []
Running command in /tmp/test: [/home/codeql/codeql/javascript/tools/autobuild.sh]
[2024-03-19 11:37:18] [build-stdout] Single-threaded extraction.
[2024-03-19 11:37:30] [build-stdout] ui/apps/platform/package.json: Main file set to ui/apps/platform/src/index.tsx
[2024-03-19 11:37:30] [build-stdout] ui/packages/tailwind-config/package.json: Main file set to ui/packages/tailwind-config/tailwind.config.js
[2024-03-19 11:37:30] [build-stdout] ui/packages/ui-components/package.json: Main file set to ui/packages/ui-components/src/index.ts
[2024-03-19 11:37:30] [build-stdout] tests/performance/package.json: Main file not found
[2024-03-19 11:37:30] [build-stdout] ui/package.json: Main file not found
[2024-03-19 11:37:33] [build-stdout] Extracting /tmp/test/ui/apps/platform/public/index.html
[2024-03-19 11:37:33] [build-stdout] Done extracting /tmp/test/ui/apps/platform/public/index.html (93 ms)
[2024-03-19 11:37:33] [build-stdout] Extracting /tmp/test/mcsutil/central/login/authorize.html
[2024-03-19 11:37:33] [build-stdout] Done extracting /tmp/test/mcsutil/central/login/authorize.html (15 ms)
[2024-03-19 11:37:33] [build-stdout] Found Node.js at: node
[2024-03-19 11:37:33] [build-stdout] Found Node.js version: v21.4.0
[2024-03-19 11:37:33] [build-stdout] Memory for TypeScript process: 2000 MB, and 400 MB reserve
[2024-03-19 11:37:34] [build-stderr] Warning: Ignoring extra certs from `/usr/local/share/ca-certificates/mts-cert.crt`, load failed: error:8000000D:system library::Permission denied
[2024-03-19 11:37:35] [build-stdout] Opening project /tmp/test/ui/apps/platform/tsconfig.json
[2024-03-19 11:37:55] [build-stdout] Done opening project /tmp/test/ui/apps/platform/tsconfig.json (20004 ms)
[2024-03-19 11:37:57] [build-stdout] Extracting /tmp/test/ui/apps/platform/src/Components/_DSMap/Filter/components/FilterControls/DateTimeFilterControl/DatePicker/Cell/Cell.tsx
[2024-03-19 11:37:57] [build-stdout] Done extracting /tmp/test/ui/apps/platform/src/Components/_DSMap/Filter/components/FilterControls/DateTimeFilterControl/DatePicker/Cell/Cell.tsx (121 ms)
[2024-03-19 11:37:57] [build-stdout] Extracting /tmp/test/ui/apps/platform/src/Components/_DSMap/Filter/components/FilterControls/DateTimeFilterControl/DatePicker/Cell/index.ts
[2024-03-19 11:37:57] [build-stdout] Done extracting /tmp/test/ui/apps/platform/src/Components/_DSMap/Filter/components/FilterControls/DateTimeFilterControl/DatePicker/Cell/index.ts (8 ms)
[2024-03-19 11:37:57] [build-stdout] Extracting /tmp/test/ui/apps/platform/src/Components/_DSMap/Filter/components/FilterControls/DateTimeFilterControl/DatePicker/Cell/types.ts
[2024-03-19 11:37:57] [build-stdout] Done extracting /tmp/test/ui/apps/platform/src/Components/_DSMap/Filter/components/FilterControls/DateTimeFilterControl/DatePicker/Cell/types.ts (12 ms)
...
```

Also if i try to run `/home/codeql/codeql/javascript/tools/autobuild.sh` with exported variables like `CODEQL_EXTRACTOR_JAVASCRIPT_ROOT`, `CODEQL_JAVA_HOME`, `ODASA_JAVASCRIPT_LAYOUT` and so on - extraction also is successful.

Of course Node is installed and present in `PATH`.
Looks like it's can be a Java runtime issue (may be with the spawn process mechanism or something like that) with incorrect set of environment.
I tried to play with `JAVA_OPTS` with `-Djdk.lang.Process.launchMechanism` but no success.

Please help me to locate and fix this issue. CodeQL binary versions used: 2.15.5 and 2.16.3.
Thank you!

**Comment by st1ckyf1ng4z** [comment]
Fixed by replacing `jvm_args` in `/home/codeql/codeql/javascript/tools/autobuild.sh`:

```jvm_args="-Xss16m -Djdk.lang.Process.launchMechanism=vfork"```
