### ISSUE TITLE
Fatal Internal Error

### ISSUE THREAD

**Issue by KylerKatz** [github/codeql#16190]
Hello, 

I am currently getting this error when trying to run my queries. In the past, I tend to get a language server-related error about once a week that usually resolves itself in 12 hours however, I have had this one for the past day. I have created my database multiple times and that seems to be working correctly. However, when I go to analyze it I get this. 

```
Oops! A fatal internal error occurred. Details:
java.lang.NullPointerException: Cannot invoke "com.semmle.frontend.binding.entities.QLType.isSubtypeOf(com.semmle.frontend.analysis.binding2.QLBindingContext2, com.semmle.frontend.binding.entities.QLType)" because the return value of "java.util.List.get(int)" is null
        at com.semmle.frontend.analysis.binding2.PredicateBodyEnv.isPrimitiveCompatibleWith(PredicateBodyEnv.java:769)
        at com.semmle.frontend.analysis.binding2.PredicateBodyEnv.resolveMethodCall(PredicateBodyEnv.java:750)
        at com.semmle.frontend.analysis.binding2.PredicateBodyEnv.resolveCallTargetsImpl(PredicateBodyEnv.java:632)
        at com.semmle.frontend.analysis.binding2.PredicateBodyEnv.lambda$new$12(PredicateBodyEnv.java:130)
        at com.semmle.frontend.analysis.binding2.BindingCache$CacheImpl.get(BindingCache.java:347)
        at com.semmle.frontend.analysis.binding2.PredicateBodyEnv.resolveCallTargets(PredicateBodyEnv.java:200)
        at com.semmle.frontend.ast.Call.getWeakBindings(Call.java:65)
        at com.semmle.frontend.analysis.binding.ReferenceBindingCheck.visit(ReferenceBindingCheck.java:95)
        at com.semmle.frontend.ast.visit.DefaultTermExprVisitor.visit(DefaultTermExprVisitor.java:127)
        at com.semmle.frontend.ast.visit.DefaultTermExprVisitor.visit(DefaultTermExprVisitor.java:49)
        at com.semmle.frontend.ast.CallTerm.accept(CallTerm.java:21)
        at com.semmle.frontend.ast.visit.DefaultTermExprVisitor.lambda$visitConnectiveDefault$0(DefaultTermExprVisitor.java:89)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at com.semmle.frontend.ast.visit.DefaultTermExprVisitor.visitConnectiveDefault(DefaultTermExprVisitor.java:89)
        at com.semmle.frontend.ast.visit.DefaultTermExprVisitor.visit(DefaultTermExprVisitor.java:84)
        at com.semmle.frontend.ast.visit.DefaultTermExprVisitor.visit(DefaultTermExprVisitor.java:49)
        at com.semmle.frontend.ast.Conjunction.accept(Conjunction.java:15)
        at com.semmle.frontend.ast.visit.DefaultTermExprVisitor.visitQuantifierTermDefault(DefaultTermExprVisitor.java:113)
        at com.semmle.frontend.ast.visit.DefaultTermExprVisitor.visit(DefaultTermExprVisitor.java:94)
        at com.semmle.frontend.ast.visit.DefaultTermExprVisitor.visit(DefaultTermExprVisitor.java:49)
        at com.semmle.frontend.ast.ExistsTerm.accept(ExistsTerm.java:10)
        at com.semmle.frontend.ast.visit.DefaultVisitor.visitPredicateDeclarationDefault(DefaultVisitor.java:189)
        at com.semmle.frontend.ast.visit.DefaultVisitor.visit(DefaultVisitor.java:164)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at java.base/java.util.Collections$UnmodifiableCollection.forEach(Unknown Source)
        at com.semmle.frontend.ast.visit.DefaultVisitor.visit(DefaultVisitor.java:73)
        at com.semmle.frontend.analysis.binding.ReferenceBindingCheck.visit(ReferenceBindingCheck.java:69)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at com.semmle.frontend.ast.visit.DefaultVisitor.visit(DefaultVisitor.java:54)
        at com.semmle.frontend.analysis.base.ReportASTVisitor.visitInside(ReportASTVisitor.java:120)
        at com.semmle.frontend.analysis.base.ReportASTVisitor.visit(ReportASTVisitor.java:108)
        at com.semmle.frontend.analysis.binding.QLBindingPass.lambda$visit$0(QLBindingPass.java:27)
        at com.semmle.frontend.analysis.binding.QLBindingPass.visitModuleOrSignature(QLBindingPass.java:56)
        at com.semmle.frontend.analysis.binding.QLBindingPass.visit(QLBindingPass.java:27)
        at com.semmle.frontend.analysis.binding.ReferenceBindingCheck.run(ReferenceBindingCheck.java:56)
        at com.semmle.frontend.Binder.checkErrors(Binder.java:113)
        at com.semmle.frontend.Binder.process(Binder.java:65)
        at com.semmle.frontend.SimpleBinder.getBindingFor(SimpleBinder.java:87)
        at com.semmle.frontend.SimpleBinder.getBindingFor(SimpleBinder.java:34)
        at com.semmle.cli2.ql.CompilationCommon$OneCompilation.lambda$compileInner$0(CompilationCommon.java:341)
        at com.semmle.cli2.ql.CompilationCommon$OneCompilation.compileInner(CompilationCommon.java:424)
        at com.semmle.cli2.ql.CompilationCommon$OneCompilation.compile(CompilationCommon.java:268)
        at com.semmle.cli2.ql.CompilationCommon.compile(CompilationCommon.java:236)
        at com.semmle.cli2.ql.CompilationCommon.compile(CompilationCommon.java:228)
        at com.semmle.cli2.execute.ExecuteQueriesCommand.compileOrLoad(ExecuteQueriesCommand.java:728)
        at com.semmle.cli2.execute.ExecuteQueriesCommand$ExecutionIterator.start(ExecuteQueriesCommand.java:189)
        at com.semmle.cli2.execute.ExecuteQueriesCommand$ExecutionIterator.lambda$next$0(ExecuteQueriesCommand.java:161)
        at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:248)
        at com.semmle.util.concurrent.Paralleliser.lambda$startMoreJobs$3(Paralleliser.java:117)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
        ```

**Comment by mbg** [comment]
Hi @KylerKatz 👋 

Can you confirm which version of CodeQL you are using, how you are creating the database, and which exact command you are getting this error on?

**Comment by KylerKatz** [comment]
Version - 2.16.3
codeql database create ${db} --language=java --source-root=${sourcePath}
codeql database analyze ${db} --format=sarifv2.1.0 --output=out.sarif --rerun codeql/codeql-custom-queries-java

Looking at the logs, I get the error from the query server

[2024-04-11 09:57:23] [PROGRESS] execute query-server2> Error running query
[2024-04-11 09:57:23] [ERROR] Error running query

**Comment by mbg** [comment]
Thanks for the extra detail! Could you try updating to the latest version of CodeQL and see if you still get this error when running the commands?

**Comment by KylerKatz** [comment]
Thank you, updating to 2.17.0 fixed it.
