### ISSUE TITLE
`IllegalArgumentException` thrown from `IMBStorage.loadIdsAndPool` during query execution attempt

### ISSUE THREAD

**Issue by akayangel218** [github/codeql#16295]
**Description of the issue**

For every CodeQL query suite I have, every one I run on my database showcases this error:

```
[2024-04-21 11:43:43] [PROGRESS] execute query-server2> Error running query
[2024-04-21 11:43:43] [ERROR] Error running query
                              java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: newPosition < 0: (-272777233 < 0)
                              	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
                              	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
                              	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
                              	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
                              	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager$WaitingEntry.lambda$error$1(QueryServer2BackendManager.java:223)
                              	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
                              	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
                              	at java.base/java.lang.Thread.run(Unknown Source)
                              Caused by: java.lang.IllegalArgumentException: newPosition < 0: (-272777233 < 0)
                              	at java.base/java.nio.Buffer.createPositionException(Unknown Source)
                              	at java.base/java.nio.Buffer.position(Unknown Source)
                              	at java.base/java.nio.ByteBuffer.position(Unknown Source)
                              	at java.base/java.nio.MappedByteBuffer.position(Unknown Source)
                              	at java.base/java.nio.MappedByteBuffer.position(Unknown Source)
                              	at com.semmle.inmemory.util.MMapPage.openFile(MMapPage.java:149)
                              	at com.semmle.inmemory.util.MMapPage.readFrom(MMapPage.java:67)
                              	at com.semmle.inmemory.util.DiskWritableStringStore.readPageFromDisk(DiskWritableStringStore.java:105)
                              	at com.semmle.inmemory.util.DiskWritableStringStore.readFrom(DiskWritableStringStore.java:54)
                              	at com.semmle.inmemory.util.SequentialDiskPool.fromRoot(SequentialDiskPool.java:107)
                              	at com.semmle.inmemory.stringpool.ExtensionalGeneration.readFromInfoFile(ExtensionalGeneration.java:328)
                              	at com.semmle.inmemory.stringpool.StringPool.loadDirectories(StringPool.java:78)
                              	at com.semmle.inmemory.populate.IMBStorage.loadIdsAndPool(IMBStorage.java:161)
                              	at com.semmle.inmemory.MemoryBackend.<init>(MemoryBackend.java:140)
                              	at com.semmle.cli2.ql.EvaluationCommon.<init>(EvaluationCommon.java:99)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.createBackend(QueryServer2BackendManager.java:192)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager$WaitingEntry.create(QueryServer2BackendManager.java:215)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.scheduleUnblockedTasks(QueryServer2BackendManager.java:265)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.withDB(QueryServer2BackendManager.java:175)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.withDBShared(QueryServer2BackendManager.java:75)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$runQuery$26(QueryServer2Command.java:584)
                              	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:248)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$runQuery$28(QueryServer2Command.java:564)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$withProgressAndCancellation$15(QueryServer2Command.java:409)
                              	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:248)
                              	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$withProgressAndCancellation$16(QueryServer2Command.java:408)
                              	... 3 common frames omitted
Apr 21, 2024 11:43:43 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError

SEVERE: Internal error: java.lang.IllegalArgumentException: newPosition < 0: (-272777233 < 0)
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: newPosition < 0: (-272777233 < 0)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager$WaitingEntry.lambda$error$1(QueryServer2BackendManager.java:223)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: newPosition < 0: (-272777233 < 0)
	at java.base/java.nio.Buffer.createPositionException(Unknown Source)
	at java.base/java.nio.Buffer.position(Unknown Source)
	at java.base/java.nio.ByteBuffer.position(Unknown Source)
	at java.base/java.nio.MappedByteBuffer.position(Unknown Source)
	at java.base/java.nio.MappedByteBuffer.position(Unknown Source)
	at com.semmle.inmemory.util.MMapPage.openFile(MMapPage.java:149)
	at com.semmle.inmemory.util.MMapPage.readFrom(MMapPage.java:67)
	at com.semmle.inmemory.util.DiskWritableStringStore.readPageFromDisk(DiskWritableStringStore.java:105)
	at com.semmle.inmemory.util.DiskWritableStringStore.readFrom(DiskWritableStringStore.java:54)
	at com.semmle.inmemory.util.SequentialDiskPool.fromRoot(SequentialDiskPool.java:107)
	at com.semmle.inmemory.stringpool.ExtensionalGeneration.readFromInfoFile(ExtensionalGeneration.java:328)
	at com.semmle.inmemory.stringpool.StringPool.loadDirectories(StringPool.java:78)
	at com.semmle.inmemory.populate.IMBStorage.loadIdsAndPool(IMBStorage.java:161)
	at com.semmle.inmemory.MemoryBackend.<init>(MemoryBackend.java:140)
	at com.semmle.cli2.ql.EvaluationCommon.<init>(EvaluationCommon.java:99)
	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.createBackend(QueryServer2BackendManager.java:192)
	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager$WaitingEntry.create(QueryServer2BackendManager.java:215)
	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.scheduleUnblockedTasks(QueryServer2BackendManager.java:265)
	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.withDB(QueryServer2BackendManager.java:175)
	at com.semmle.cli2.execute.queryServer2.QueryServer2BackendManager.withDBShared(QueryServer2BackendManager.java:75)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$runQuery$26(QueryServer2Command.java:584)
	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:248)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$runQuery$28(QueryServer2Command.java:564)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$withProgressAndCancellation$15(QueryServer2Command.java:409)
	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:248)
	at com.semmle.cli2.execute.queryServer2.QueryServer2Command$Impl.lambda$withProgressAndCancellation$16(QueryServer2Command.java:408)
	... 3 more


Error running query: Internal error. (codeQLQueries.runLocalQueryFromQueriesPanel)
Error: Error running query: Internal error.
    at handleResponse (c:\Users\kidus\.vscode\extensions\github.vscode-codeql-1.12.5\out\extension.js:37419:40)
    at handleMessage (c:\Users\kidus\.vscode\extensions\github.vscode-codeql-1.12.5\out\extension.js:37229:11)
    at processMessageQueue (c:\Users\kidus\.vscode\extensions\github.vscode-codeql-1.12.5\out\extension.js:37244:13)
    at Immediate.<anonymous> (c:\Users\kidus\.vscode\extensions\github.vscode-codeql-1.12.5\out\extension.js:37220:11)
    at processImmediate (node:internal/timers:476:21)
```

Is there a fix to this I can make to get them to work?
```[tasklist]
### Tasks
```

**Comment by akayangel218** [comment]
I ran the same thing on CodeQL CLI and got the following:

`Oops! A fatal internal error occurred. Details:
java.lang.IllegalArgumentException: newPosition < 0: (-272777233 < 0)
        at java.base/java.nio.Buffer.createPositionException(Unknown Source)
        at java.base/java.nio.Buffer.position(Unknown Source)
        at java.base/java.nio.ByteBuffer.position(Unknown Source)
        at java.base/java.nio.MappedByteBuffer.position(Unknown Source)
        at java.base/java.nio.MappedByteBuffer.position(Unknown Source)
        at com.semmle.inmemory.util.MMapPage.openFile(MMapPage.java:149)
        at com.semmle.inmemory.util.MMapPage.readFrom(MMapPage.java:67)
        at com.semmle.inmemory.util.DiskWritableStringStore.readPageFromDisk(DiskWritableStringStore.java:105)
        at com.semmle.inmemory.util.DiskWritableStringStore.readFrom(DiskWritableStringStore.java:54)
        at com.semmle.inmemory.util.SequentialDiskPool.fromRoot(SequentialDiskPool.java:107)
        at com.semmle.inmemory.stringpool.ExtensionalGeneration.readFromInfoFile(ExtensionalGeneration.java:328)
        at com.semmle.inmemory.stringpool.StringPool.loadDirectories(StringPool.java:78)
        at com.semmle.inmemory.populate.IMBStorage.loadIdsAndPool(IMBStorage.java:161)
        at com.semmle.inmemory.MemoryBackend.<init>(MemoryBackend.java:144)
        at com.semmle.cli2.ql.EvaluationCommon.<init>(EvaluationCommon.java:91)
        at com.semmle.cli2.ql.EvaluationCommon.<init>(EvaluationCommon.java:68)
        at com.semmle.cli2.execute.ExecuteQueriesCommand.executeSubcommand(ExecuteQueriesCommand.java:413)
        at com.semmle.cli2.picocli.SubcommandCommon.lambda$executeSubcommandWithMessages$5(SubcommandCommon.java:803)    
        at com.semmle.cli2.picocli.SubcommandCommon.withCompilationMessages(SubcommandCommon.java:442)
        at com.semmle.cli2.picocli.SubcommandCommon.executeSubcommandWithMessages(SubcommandCommon.java:801)
        at com.semmle.cli2.picocli.SubcommandCommon.toplevelMain(SubcommandCommon.java:685)
        at com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:666)
        at com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:237)
        at com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:257)
        at com.semmle.cli2.CodeQL.main(CodeQL.java:115)`

**Comment by smowton** [comment]
Does a `codeql database cleanup -m clear` help? The VSCode equivalent is the CodeQL: Clear cache command.

**Comment by akayangel218** [comment]
I tried that and got this:

Cleaning up existing TRAP files after import...
TRAP files cleaned up (0ms).
Cleaning up scratch directory...
Scratch directory cleaned up (14ms).
A fatal error occurred: Error cleaning directory 'C:\Users\kidus\5590\insecuredataset\cpy20\db-python\default\cache'
(eventual cause: MultiIOException "java.nio.file.FileSystemException: C:\Users\kidus\5590\insecuredataset\cpy20\db-...")

**Comment by hmakholm** [comment]
The stack traces in the original error suggest that the database is corrupted in some way that is probably not recoverable. How that happened we may never know; I think your best chance will be to generate the database afresh from the original source tree.
