### ISSUE TITLE
TypeScript Parsing Error

### ISSUE THREAD

**Issue by aydinnyunus** [github/codeql#16347]
I have an error when creating the database.

```
[2024-04-26 21:48:38] [build-stdout] Done extracting /home/ubuntu/xxx/xxx/xxx/package/README.hbs (0 ms)
[2024-04-26 21:48:38] [build-stdout] Found Node.js at: node
[2024-04-26 21:48:38] [build-stdout] Found Node.js version: v10.19.0
[2024-04-26 21:48:38] [build-stdout] Memory for TypeScript process: 2000 MB, and 400 MB reserve
[2024-04-26 21:48:38] [build-stderr] /home/ubuntu/codeql/codeql/javascript/tools/typescript-parser-wrapper/node_modules/typescript/lib/typescript.js:139
[2024-04-26 21:48:38] [build-stderr]     for (let i = startIndex ?? 0; i < array.length; i++) {
[2024-04-26 21:48:38] [build-stderr]                              ^
[2024-04-26 21:48:38] [build-stderr] SyntaxError: Unexpected token ?
[2024-04-26 21:48:38] [build-stderr]     at Module._compile (internal/modules/cjs/loader.js:723:23)
[2024-04-26 21:48:38] [build-stderr]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[2024-04-26 21:48:38] [build-stderr]     at Module.load (internal/modules/cjs/loader.js:653:32)
[2024-04-26 21:48:38] [build-stderr]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[2024-04-26 21:48:38] [build-stderr]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[2024-04-26 21:48:38] [build-stderr]     at Module.require (internal/modules/cjs/loader.js:692:17)
[2024-04-26 21:48:38] [build-stderr]     at require (internal/modules/cjs/helpers.js:25:18)
[2024-04-26 21:48:38] [build-stderr]     at Object.<anonymous> (/home/ubuntu/codeql/codeql/javascript/tools/typescript-parser-wrapper/typescript.js:6:22)
[2024-04-26 21:48:38] [build-stderr]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[2024-04-26 21:48:38] [build-stderr]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[2024-04-26 21:48:38] [build-stderr] com.semmle.util.exception.CatastrophicError: The TypeScript parser wrapper crashed with exit code 1
[2024-04-26 21:48:38] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.getExceptionFromMalformedResponse(TypeScriptParser.java:399)
[2024-04-26 21:48:38] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.talkToParserWrapper(TypeScriptParser.java:364)
[2024-04-26 21:48:38] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.loadMetadata(TypeScriptParser.java:416)
[2024-04-26 21:48:38] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.setupParserWrapper(TypeScriptParser.java:320)
[2024-04-26 21:48:38] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.talkToParserWrapper(TypeScriptParser.java:351)
[2024-04-26 21:48:38] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.getOwnFiles(TypeScriptParser.java:494)
[2024-04-26 21:48:38] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.extractTypeScript(AutoBuild.java:1029)
[2024-04-26 21:48:38] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.extractSource(AutoBuild.java:755)
[2024-04-26 21:48:38] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.run(AutoBuild.java:462)
[2024-04-26 21:48:38] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.main(AutoBuild.java:1352)
[2024-04-26 21:48:38] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/home/ubuntu/codeql/codeql/javascript/tools/autobuild.sh])
A fatal error occurred: Exit status 1 from command: [/home/ubuntu/codeql/codeql/javascript/tools/autobuild.sh]
```

**Comment by jketema** [comment]
Hi @aydinnyunus,

To run CodeQL you'll need at least Node.js 14 (see [here](https://codeql.github.com/docs/codeql-overview/system-requirements/)). You appear to be running Node.js 10

**Comment by aydinnyunus** [comment]
Hi @jketema,

Thank you for quick response. After updating the node version it is fixed 🙏
