### ISSUE TITLE
TypeScriptParser error

### ISSUE THREAD

**Issue by kexinoh** [github/codeql#16357]
**Description of the issue**
i do it in ubuntu,and node.js=20.12.0.

[2024-04-29 14:08:41] [build-stdout] Extracting /home/hhh/JScodeql/extractead_packages/@superfluid-finance/sdk-core/package/dist/main/subgraph/subgraphQueryHandler.d.ts
[2024-04-29 14:08:41] [build-stderr] Exception while extracting /home/hhh/JScodeql/extracted_packages/@superfluid-finance/sdk-core/package/dist/main/subgraph/subgraphQueryHandler.d.ts.
[2024-04-29 14:08:41] [build-stderr] com.semmle.util.exception.CatastrophicError: The TypeScript parser wrapper crashed with exit code 129
[2024-04-29 14:08:41] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.getExceptionFromMalformedResponse(TypeScriptParser.java:399)
[2024-04-29 14:08:41] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.talkToParserWrapper(TypeScriptParser.java:354)
[2024-04-29 14:08:41] [build-stderr] 	at com.semmle.ts.extractor.TypeScriptParser.parse(TypeScriptParser.java:434)
[2024-04-29 14:08:41] [build-stderr] 	at com.semmle.js.extractor.TypeScriptExtractor.extract(TypeScriptExtractor.java:24)
[2024-04-29 14:08:41] [build-stderr] 	at com.semmle.js.extractor.FileExtractor.extractContents(FileExtractor.java:553)
[2024-04-29 14:08:41] [build-stderr] 	at com.semmle.js.extractor.FileExtractor.extract(FileExtractor.java:460)
[2024-04-29 14:08:41] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.doExtract(AutoBuild.java:1247)
[2024-04-29 14:08:41] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.extract(AutoBuild.java:1228)
[2024-04-29 14:08:41] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.extractTypeScriptFiles(AutoBuild.java:1181)
[2024-04-29 14:08:41] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.extractTypeScript(AutoBuild.java:1078)
[2024-04-29 14:08:41] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.extractSource(AutoBuild.java:755)
[2024-04-29 14:08:41] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.run(AutoBuild.java:462)
[2024-04-29 14:08:41] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.main(AutoBuild.java:1352)
[2024-04-29 14:08:41] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/home/hhh/codeql/javascript/tools/autobuild.sh])
[2024-04-29 14:08:41] Exception caught at top level: Exit status 1 from command: [/home/hhh/codeql/javascript/tools/autobuild.sh]
                      com.semmle.cli2.Commandline.executeAndCheckResult(Commandline.java:170)
                      com.semmle.cli2.Commandline.runWithoutReturn(Commandline.java:123)
                      com.semmle.cli2.database.DatabaseProcessCommandCommon.executeSubcommand(DatabaseProcessCommandCommon.java:228)
                      com.semmle.cli2.database.TraceCommandCommand.executeSubcommand(TraceCommandCommand.java:126)
                      com.semmle.cli2.picocli.SubcommandCommon.lambda$executeSubcommandWithMessages$5(SubcommandCommon.java:803)
                      com.semmle.cli2.picocli.SubcommandCommon.withCompilationMessages(SubcommandCommon.java:442)
                      com.semmle.cli2.picocli.SubcommandCommon.executeSubcommandWithMessages(SubcommandCommon.java:801)
                      com.semmle.cli2.picocli.PlumbingRunner.run(PlumbingRunner.java:119)
                      com.semmle.cli2.picocli.SubcommandCommon.runPlumbingInProcess(SubcommandCommon.java:199)
                      com.semmle.cli2.database.CreateCommand.executeSubcommand(CreateCommand.java:181)
         
 com.semmle.cli2.picocli.SubcommandCommon.lambda$executeSubcommandWithMessages$5(SubcommandCommon.java:803)
                      com.semmle.cli2.picocli.SubcommandCommon.withCompilationMessages(SubcommandCommon.java:442)
                      com.semmle.cli2.picocli.SubcommandCommon.executeSubcommandWithMessages(SubcommandCommon.java:801)
                      com.semmle.cli2.picocli.SubcommandCommon.toplevelMain(SubcommandCommon.java:685)
                      com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:666)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:237)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:257)
                      com.semmle.cli2.CodeQL.main(CodeQL.java:115)
`

**Comment by ginsbach** [comment]
Thank you for reporting this.

Can you please provide some more context:
- Which version of codeql are you using?
- What is the repository you are working on?
- What exactly did you do to get the crash?
