### ISSUE TITLE
CodeQL autobuild action doesn't work with reusable workflow

### ISSUE THREAD

**Issue by tacascer** [github/codeql#16536]
**Description of the issue**

# What

Is [this](https://github.com/tacascer-org/xml-processor/actions/runs/9166282881/job/25206749355?pr=74) workflow, CodeQL is giving an error:

```
##[debug]Failed to upload a SARIF file for this failed CodeQL code scanning run. Error: Could not get upload input to github/codeql-action/analyze since the workflow has no job named run-codeql-analysis.
```

At the end, it also gives this error
```
 CodeQL job status was configuration error.
##[debug]Sending status report: {"action_name":"init-post","action_oid":"unknown","action_ref":"v3","action_started_at":"2024-05-21T03:16:14.586Z","action_version":"3.25.6","analysis_key":".github/workflows/build.yml:run-codeql-analysis","commit_oid":"b2fae2e702ab1ab745e7259f3b4941ee7eef9bcc","first_party_analysis":true,"job_name":"run-codeql-analysis","job_run_uuid":"ed23c847-a30b-4f6f-a506-1e6a99197373","ref":"refs/pull/74/merge","runner_os":"Linux","started_at":"2024-05-21T03:14:28.532Z","status":"success","testing_environment":"","workflow_name":"Build","workflow_run_attempt":2,"workflow_run_id":9166282881,"actions_event_name":"pull_request","languages":"java","runner_available_disk_space_bytes":19179081728,"runner_total_disk_space_bytes":77851254784,"completed_at":"2024-05-21T03:16:18.466Z","matrix_vars":"null","runner_arch":"X64","runner_image_version":"20240516.1.0","upload_failed_run_error":"Could not get upload input to github/codeql-action/analyze since the workflow has no job named run-codeql-analysis.","upload_failed_run_stack_trace":"Error: Could not get upload input to github/codeql-action/analyze since the workflow has no job named run-codeql-analysis.\n    at getInputOrThrow (/home/runner/work/_actions/github/codeql-action/v3/lib/workflow.js:263:15)\n    at getUploadInputOrThrow (/home/runner/work/_actions/github/codeql-action/v3/lib/workflow.js:323:12)\n    at maybeUploadFailedSarif (/home/runner/work/_actions/github/codeql-action/v3/lib/init-action-post-helper.js:57:63)\n    at async tryUploadSarifIfRunFailed (/home/runner/work/_actions/github/codeql-action/v3/lib/init-action-post-helper.js:92:20)\n    at async Object.run (/home/runner/work/_actions/github/codeql-action/v3/lib/init-action-post-helper.js:108:37)\n    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v3/lib/init-action-post.js:57:35)","job_status":"JOB_STATUS_CONFIGURATION_ERROR"}
```

I suspect this is because the workflow actually uses a reusable workflow defined [here](https://github.com/tacascer-org/actions-workflows/blob/main/.github/workflows/gradle_build.yml#L52-L68).

The job `run-codeql-analysis` is defined in the reusable workflow but not in the calling workflow.

**Comment by tacascer** [comment]
Solution: I had to also run the `github/codeql-action/analyze@v2` after the autobuild
