### ISSUE TITLE
CodeQL Scanning | Java-Kotlin | Error when parsing property file 'log\ext\javac.properties' | com.semmle.util.io.properties.PropertiesReader$ParseException: Unable to parse unicode value: 'sr\l' @ line 6 column 16

### ISSUE THREAD

**Issue by PCStefan** [github/codeql#16874]
## **Summary**
I am trying to analyse an Android project written in Kotlin.
But CodeQL fails to complete analysis as it is crashing with the following exception:
```
[ERROR] Error when parsing property file 'C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android\.codeql-db-manual\log\ext\javac.properties'!
[2024-06-27 14:08:45] [build-stdout] [2024-06-27 14:08:45] [build-stdout]                               com.semmle.util.io.properties.PropertiesReader$ParseException: Unable to parse unicode value: 'sr\l' @ line 6 column 16
```

## **Tools, versions and environment**

<details>
  <summary>
     Expand to see the `with` section used to run codeql
  </summary>

```
with: 
  category: /language:java-kotlin 
  output: ../results 
  upload: always 
  cleanup-level: brutal 
  add-snippets: false 
  skip-queries: false 
  checkout_path: /home/runner/work/SS.android/SS.android 
   upload-database: true 
   wait-for-processing: true 
   token: *** 
   matrix: { 
     "java": "17", 
     "language": "java-kotlin", 
     "build-mode": "manual" 
   } 
   expect-error: false 
   env: 
     JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64 
     JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.11-9/x64 
     CODEQL_ACTION_FEATURE_MULTI_LANGUAGE: false 
     CODEQL_ACTION_FEATURE_SANDWICH: false 
     CODEQL_ACTION_FEATURE_SARIF_COMBINE: true 
     CODEQL_ACTION_FEATURE_WILL_UPLOAD: true 
     CODEQL_ACTION_VERSION: 3.25.10 
     JOB_RUN_UUID: 437daa1e-13df-447a-920d-1cfd8b35c6cf 
     CODEQL_ACTION_INIT_HAS_RUN: true 
     CODEQL_ACTION_ANALYSIS_KEY: .github/workflows/codeql.yml:analyze 
     CODEQL_WORKFLOW_STARTED_AT: 2024-06-18T19:44:01.072Z 
     CODEQL_RAM: 6905 
     CODEQL_THREADS: 2 
/opt/hostedtoolcache/CodeQL/2.17.5/x64/codeql/codeql version --format=json 
   { 
       "productName" : "CodeQL", 
       "vendor" : "GitHub", 
       "version" : "2.17.5", 
       "sha" : "0ee7464b4be95bced213b1f3892929d427edb9a0", 
       "branches" : [ 
          "codeql-cli-2.17.5" 
       ], 
       "copyright" : "Copyright (C) 2019-2024 GitHub, Inc.", 
       "unpackedLocation" : "/opt/hostedtoolcache/CodeQL/2.17.5/x64/codeql", 
       "configFileLocation" : "/home/runner/.config/codeql/config", 
       "configFileFound" : false, 
       "features" : { 
          "analysisSummaryV2Default" : true, 
          "buildModeOption" : true, 
          "bundleSupportsIncludeDiagnostics" : true, 
          "featuresInVersionResult" : true, 
          "indirectTracingSupportsStaticBinaries" : false, 
          "informsAboutUnsupportedPathFilters" : true, 
          "supportsPython312" : true, 
          "mrvaPackCreate" : true, 
          "threatModelOption" : true, 
          "traceCommandUseBuildMode" : true, 
          "v2ramSizing" : true, 
          "mrvaPackCreateMultipleQueries" : true, 
          "setsCodeqlRunnerEnvVar" : true, 
          "sarifMergeRunsFromEqualCategory" : true 
       }  
   }
```

</details>

## **Steps to replicate**
I have tried many ways to build it
<details><summary>
GitHub Actions with build-mode `auto`
</summary>
it tried to analyse the project as `ruby` 
</details>

<details><summary>
GitHub Actions with build-mode `none` 
</summary>
it failed to compile the project and suggested me to use build-mode: `manual`

```
5583 /opt/hostedtoolcache/CodeQL/2.17.5/x64/codeql/codeql database finalize --finalize-dataset --threads=2 --ram=6905 /home/runner/work/_temp/codeql_databases/java

5584 CodeQL detected code written in Java/Kotlin but could not process any of it using the 'none' build mode. Set up manual build steps (see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#about-specifying-build-steps-manually) or check the workflow run logs (see https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/using-workflow-run-logs). For more information, review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build . 

5585 Error: Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.17.5/x64/codeql/codeql database finalize --finalize-dataset --threads=2 --ram=6905 /home/runner/work/_temp/codeql_databases/java". Exit code was 32 and last log line was: CodeQL detected code written in Java/Kotlin but could not process any of it using the 'none' build mode. Set up manual build steps (see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#about-specifying-build-steps-manually) or check the workflow run logs (see https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/using-workflow-run-logs). For more information, review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build . See the logs for more details.

```

</details>

<details><summary>
GitHub Actions with build-mode `manual` 
</summary>
the project is built/compiled,   
The analysis bit is timing out (no error shown) because it is getting stuck at a single step.

</details>

So, I have downloaded the CodeQL binaries v2.17.5 and tried to run the scan locally:
  > codeql database create ./.codeql-db-none --build-mode="none" --language="java-kotlin"
  > codeql database create ./.codeql-db-manual --command "gradlew app:buildInternal" --language="java-kotlin"
 
The local execution fails with the following error:
```
Finalizing database at C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android\.codeql-db-manual.
Running pre-finalize script C:\Work\Tools\CodeQL\codeql\java\tools\pre-finalize.cmd in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android.
Running command in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android: [C:\Work\Tools\CodeQL\codeql\java\tools\pre-finalize.cmd]
[2024-06-25 12:17:19] [build-stderr] Scanning for files in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android...
[2024-06-25 12:17:23] [build-stderr] C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android\.codeql-db-manual: Indexing files in in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android...
[2024-06-25 12:17:23] [build-stderr] Running command in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android: [C:\Work\Tools\CodeQL\codeql\xml\tools\index-files.cmd, C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android\.codeql-db-manual\working\files-to-index13102573589778143701.list]
[2024-06-25 12:17:42] [build-stderr] Scanning for files in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android...
[2024-06-25 12:17:46] [build-stderr] C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android\.codeql-db-manual: Indexing files in in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android...
[2024-06-25 12:17:46] [build-stderr] Running command in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android: [C:\Work\Tools\CodeQL\codeql\properties\tools\index-files.cmd, C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android\.codeql-db-manual\working\files-to-index7922255477567431548.list]
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [ERROR] Error when parsing property file 'C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android\.codeql-db-manual\log\ext\javac.properties'!
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                               com.semmle.util.io.properties.PropertiesReader$ParseException: Unable to parse unicode value: 'sr\l' @ line 7 column 16
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       at com.semmle.util.io.properties.PropertiesReader.parseProperty(PropertiesReader.java:321)
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       at com.semmle.util.io.properties.PropertiesReader.nextProperty(PropertiesReader.java:252)
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       at com.semmle.cli.PropertiesExtractor.extractFile(PropertiesExtractor.java:39)
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       at com.semmle.cli.SimpleExtractor.extract(SimpleExtractor.java:154)
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       at com.semmle.cli.SimpleExtractor.run(SimpleExtractor.java:54)
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       at com.semmle.cli.PropertiesExtractor.main(PropertiesExtractor.java:22)
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                               Caused by: com.semmle.util.io.properties.PropertiesReader$ParseException: Unable to parse unicode value: 'sr\l'
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       at com.semmle.util.io.properties.PropertiesReader.unescapeJava(PropertiesReader.java:491)
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       at com.semmle.util.io.properties.PropertiesReader.unescapePropertyValue(PropertiesReader.java:370)
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       at com.semmle.util.io.properties.PropertiesReader.initPropertyValue(PropertiesReader.java:359)
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       at com.semmle.util.io.properties.PropertiesReader.parseProperty(PropertiesReader.java:314)
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       ... 5 common frames omitted
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                               Caused by: java.lang.NumberFormatException: For input string: "sr\l" under radix 16
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       at java.base/java.lang.Integer.parseInt(Unknown Source)
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       at com.semmle.util.io.properties.PropertiesReader.unescapeJava(PropertiesReader.java:485)
[2024-06-25 12:17:47] [build-stdout] [2024-06-25 12:17:47] [build-stdout]                                       ... 8 common frames omitted
Running TRAP import for CodeQL database at C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android\.codeql-db-manual...
```

**Comment by jketema** [comment]
Hi @PCStefan ,

Thanks for your report. I've let the CodeQL Kotlin engineering team know about this problem.

**Comment by jketema** [comment]
Because the database directory is created below your source root, CodeQL will try to scan it and pick up on the `.properties` file that lives in the database directory. This is what your seeing here. We generally suggest to create the database directory outside of your source directory, which should resolve the error.

Note that the error is non-fatal, and CodeQL will have constructed a valid database.

It looks like there's also some other problems you're running into, can I somehow help you with those?

**Comment by PCStefan** [comment]
I have run the same 2 commands locally on my machine I did earlier, but I have updated the path of where the database should be created. I am not encountering that error anymore. However, I am still doubtful of the success of the analysis:

Please expand the 2 following sections and see results:
---

<details>
  <summary>
     [codeql database create ./../.codeql-db-manual --command "gradlew app:buildInternal" --language="java-kotlin"] => ended with "could not process any of it"
  </summary>
   
```
Finalizing database at C:\BACKUP-2024\C\CompanyX\Code\18.17.1\.codeql-db-manual.

CodeQL detected code written in Java/Kotlin but could not process any of it. For more information, review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build.
```

</details>

---

<details>
  <summary>
     [codeql database create ./../.codeql-db-none --build-mode="none" --language="java-kotlin"]
 </summary>

Despite mentioning `none` as a build-mode, the logs will display `autobuild`. I can also see that within the last few logs there are few logs of `[build-stderr]` type.
   
```
$> codeql database create ./../.codeql-db-none --build-mode="none" --language="java-kotlin"

Initializing database at C:\BACKUP-2024\C\CompanyX\Code\18.17.1\.codeql-db-none.
Running build command: []
Running command in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android: [C:\Work\Tools\CodeQL\codeql\java\tools\autobuild.cmd]
[2024-06-28 14:55:00] [build-stdout] [2024-06-28 14:55:00] Extracting Java with build-mode=none.
[2024-06-28 14:55:00] [build-stdout] [2024-06-28 14:55:00] Found usable build tool Gradle.
[2024-06-28 14:55:00] [build-stdout] [2024-06-28 14:55:00] Trying to infer the JDK to use to extract Java.
[2024-06-28 14:55:00] [build-stdout] [2024-06-28 14:55:00] Found no Java toolchains in a toolchains file, inspecting environment variables...
[2024-06-28 14:55:01] [build-stdout] [2024-06-28 14:55:01] The Android plugin version in use recommends Java version 17.0.0.
[2024-06-28 14:55:01] [build-stdout] [2024-06-28 14:55:01] [WARN] The suggested lower bound Java version is 17.0.0, but no version that is equal to or greater than that is available on this system.
[2024-06-28 14:55:01] [build-stdout] [2024-06-28 14:55:01] Identified 19.0.0 as the newest version of Java supported by the version of Gradle in use. The system default of 17.0.9 is compatible with this.
[2024-06-28 14:55:01] [build-stdout] [2024-06-28 14:55:01] Found no Java toolchains in a toolchains file, inspecting environment variables...
[2024-06-28 14:55:01] [build-stdout] [2024-06-28 14:55:01] Checking if a build tool can recommend a classpath to resolve external dependencies.
[2024-06-28 14:55:02] [build-stdout] [2024-06-28 14:55:02] [autobuild] Initialized native services in: C:\Users\stefan\.gradle\native
[2024-06-28 14:55:02] [build-stdout] [2024-06-28 14:55:02] [autobuild] Initialized jansi services in: C:\Users\stefan\.gradle\native

...
...
...

[2024-06-28 14:55:24] [build-stdout] [2024-06-28 14:55:24] [autobuild] GitHubDependencyGraphRenderer: Wrote dependency snapshot to
[2024-06-28 14:55:24] [build-stdout] [2024-06-28 14:55:24] [autobuild] C:\BACKUP-2024\C\CompanyX\Code\18.17.1\.codeql-db-none\working\java-standalone-dependency-graph1762326442502019537\dep-graph.json
[2024-06-28 14:55:24] [build-stdout] [2024-06-28 14:55:24] [autobuild] BUILD SUCCESSFUL in 22s
[2024-06-28 14:55:24] [build-stdout] [2024-06-28 14:55:24] [autobuild] 2 actionable tasks: 2 executed
[2024-06-28 14:55:24] [build-stdout] [2024-06-28 14:55:24] [autobuild] Watched directory hierarchies: []
[2024-06-28 14:55:24] [build-stdout] [2024-06-28 14:55:24] Top-level projects disagree about some of their direct dependencies. The following were overridden by higher versions:
[2024-06-28 14:55:24] [build-stdout]                       * `androidx.fragment/fragment-testing-1.6.0-alpha04`
[2024-06-28 14:55:24] [build-stdout]                       * `androidx.navigation/navigation-fragment-ktx-2.5.0`
[2024-06-28 14:55:24] [build-stdout]                       * `androidx.navigation/navigation-ui-ktx-2.5.0`
[2024-06-28 14:55:24] [build-stdout]                       * `androidx.test/core-1.4.0`
[2024-06-28 14:55:24] [build-stdout]                       * `androidx.test/core-ktx-1.4.0`
[2024-06-28 14:55:24] [build-stdout]                       * `androidx.test/monitor-1.4.0`
[2024-06-28 14:55:24] [build-stdout]                       * `com.google.android.gms/play-services-location-18.0.0`
[2024-06-28 14:55:24] [build-stdout]                       * `com.google.guava/listenablefuture-1.0`
[2024-06-28 14:55:24] [build-stdout]                       * `net.bytebuddy/byte-buddy-1.9.10`
[2024-06-28 14:55:24] [build-stdout]                       * `net.bytebuddy/byte-buddy-agent-1.9.10`
[2024-06-28 14:55:24] [build-stdout]                       * `org.hamcrest/hamcrest-core-1.3`
[2024-06-28 14:55:24] [build-stdout]                       * `org.jetbrains.kotlin/kotlin-stdlib-1.7.10`
[2024-06-28 14:55:24] [build-stdout]                       * `org.jetbrains.kotlinx/kotlinx-coroutines-test-1.3.5`
[2024-06-28 14:55:24] [build-stdout]                       * `org.jetbrains.kotlinx/kotlinx-coroutines-test-1.6.4`
[2024-06-28 14:55:24] [build-stdout]                       * `org.objenesis/objenesis-2.6`
[2024-06-28 14:55:24] [build-stdout] [2024-06-28 14:55:24] No specific JDK inferred from the project being analysed; using the java on the PATH
[2024-06-28 14:55:25] [build-stdout] [2024-06-28 14:55:25] [autobuild] Scanning for files in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android...
[2024-06-28 14:55:26] [build-stdout] [2024-06-28 14:55:26] [autobuild] C:\BACKUP-2024\C\CompanyX\Code\18.17.1\.codeql-db-none: Indexing files in in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android...
[2024-06-28 14:55:26] [build-stdout] [2024-06-28 14:55:26] [autobuild] Running command in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android: [C:\Work\Tools\CodeQL\codeql\java\tools\index-files.cmd, C:\BACKUP-2024\C\CompanyX\Code\18.17.1\.codeql-db-none\working\files-to-index239971185454441485.list]
Finalizing database at C:\BACKUP-2024\C\CompanyX\Code\18.17.1\.codeql-db-none.
Running pre-finalize script C:\Work\Tools\CodeQL\codeql\java\tools\pre-finalize.cmd in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android.
Running command in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android: [C:\Work\Tools\CodeQL\codeql\java\tools\pre-finalize.cmd]
[2024-06-28 15:00:17] [build-stderr] Scanning for files in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android...
[2024-06-28 15:00:18] [build-stderr] C:\BACKUP-2024\C\CompanyX\Code\18.17.1\.codeql-db-none: Indexing files in in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android...
[2024-06-28 15:00:18] [build-stderr] Running command in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android: [C:\Work\Tools\CodeQL\codeql\xml\tools\index-files.cmd, C:\BACKUP-2024\C\CompanyX\Code\18.17.1\.codeql-db-none\working\files-to-index14990227128031818202.list]
[2024-06-28 15:00:38] [build-stderr] Scanning for files in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android...
[2024-06-28 15:00:39] [build-stderr] C:\BACKUP-2024\C\CompanyX\Code\18.17.1\.codeql-db-none: Indexing files in in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android...
[2024-06-28 15:00:39] [build-stderr] Running command in C:\BACKUP-2024\C\CompanyX\Code\18.17.1\SS.android: [C:\Work\Tools\CodeQL\codeql\properties\tools\index-files.cmd, C:\BACKUP-2024\C\CompanyX\Code\18.17.1\.codeql-db-none\working\files-to-index7568153835039947976.list]
Running TRAP import for CodeQL database at C:\BACKUP-2024\C\CompanyX\Code\18.17.1\.codeql-db-none...
Importing TRAP files
Merging relations
Finished writing database (relations: 45.35 MiB; string pool: 19.03 MiB).
TRAP import complete (15.5s).
Finished zipping source archive (5.02 MiB).
Successfully created database at C:\BACKUP-2024\C\CompanyX\Code\18.17.1\.codeql-db-none.
```

</details>

---

So, if I ignore the fact that among last few logs when running `none` build-mode I see [build-stderr] with no explanation of why, then it does not explain why it takes so long to run on the GitHub runner and why it does times out. 

So, yeah, I could appreciate if you could provide me with some few pointers to solve these issues I am experiencing.

**Comment by jketema** [comment]
For the run where you explicitly specified, as you're using gradle, you'll need to specify the `-no-daemon` option. See [this page](https://docs.github.com/en/code-security/codeql-cli/getting-started-with-the-codeql-cli/preparing-your-code-for-codeql-analysis) for details and search for gradle.

For the build mode none it is correct that the `autobuild` script is run. However, it's only use in this case is to pull in the relevant dependencies. It will not actually try to build your code. Regarding the error: it seems that you pull in different versions of certain dependencies. As CodeQL does not build your code in this case, it just assumes you wanted to use the most recent versions of those dependencies, and it warns you that it's ignoring the older versions.

**Comment by PCStefan** [comment]
Hi @jketema 

Thanks to you and the team for the help. All it is working as expected now.

Locally, as the build is persisted as I was not making any changes, I am able to run
> codeql database create ./../.codeql-db-manual --command "gradlew  --no-daemon --no-build-cache app:buildInternal" --language="java-kotlin"

On GitHub Runners, I will test without the `--no-build-cache` as the runners will built the app on a cleaned runner:
> codeql database create ./../.codeql-db-manual --command "gradlew  --no-daemon app:buildInternal" --language="java-kotlin"

Thanks again. 🌟

**Comment by jketema** [comment]
You're welcome. Closing this as completed. Feel free to reopen if that's not actually the case.
