### ISSUE TITLE
Error running query: Webview is disposed in CodeQL with Java Extension Pack

### ISSUE THREAD

**Issue by HeouDonkey** [github/codeql#16889]
Description:

I have encountered an issue when using CodeQL in Visual Studio Code, which seems to be related to the "Extension Pack for Java". Here are the details of the error and the steps I took to reproduce it:

Error Description:

The error message I received is: "Error running query: Webview is disposed (codeQL.runLocalQueryFromFileTab)".
The full error stack trace is as follows:
```
Error: Error running query: Webview is disposed
at C.c (/path/to/extensionHostProcess.js:157:51827)
at C.get visible [as visible] (/path/to/extensionHostProcess.js:157:51471)
at ResultsView.showResults (/path/to/extension.js:113926:16)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at LocalQueries.showResultsForCompletedQuery (/path/to/extension.js:113270:5)
at LocalQueryRun.complete (/path/to/extension.js:112775:5)
at LocalQueries.compileAndRunQueryInternal (/path/to/extension.js:113190:9)
at LocalQueries.compileAndRunQuery (/path/to/extension.js:113128:5)
at withProgress.title (/path/to/extension.js:112923:9)
```

**Comment by robertbrignull** [comment]
Hi, could you explain a little more about the steps needed to reproduce this? For example, what exactly did you click on or what command did you run to trigger this? What file or view was open in VS Code at the time? Had VS Code only just started up and were there any windows already open from last time you used it? Are you able to reproduce it consistently?

**Comment by robertbrignull** [comment]
@HeouDonkey, I'm going to close this issue for now as we've not heard back from you. Please do reach out if this error is still happening for you and we can re-open this issue and investigate further. 🙇
