### ISSUE TITLE
[Java Scannig] CodeQL crashing when re-using database with different bundles

### ISSUE THREAD

**Issue by chmodxxx** [github/codeql#16897]
Hello, 

We have this Circle CI flow where we build a database with a given bundle,  analyze it using bundle(1) then persist the DB to the CI workspace to re-use it afterwards. 
We then analyze the same db using bundle(2). 

Analysis with bundle(1) succeed but analysis with bundle(2) crashes even tho it's the same bundle (same CLI  version same qlpacks) , the exact stack trace is below  and the command I'm using for analysis is : 
```
codeql database analyze \
            --format=sarif-latest --output="${CODEQL_ANALYSIS_FOLDER}/${ORG}-${REPO}${SUFFIX}-results.sarif" --threads=0 \
            --rerun --no-save-cache --no-keep-full-cache \
            --tuple-counting --evaluator-log="${CODEQL_ANALYSIS_FOLDER}/${ORG}-${REPO}${SUFFIX}-evaluator-log.json" --evaluator-log-minify \
            "${CODEQL_BUILD_FOLDER}/${ORG}-${REPO}-codeql-db" codeql/java-queries octo-org/ql-java
        res=$?
```

stack trace error : 
```

[64/94 eval 2m22s] Evaluation done; writing results to codeql/java-queries/Security/CWE/CWE-134/ExternallyControlledFormatString.bqrs.
Oops! A fatal internal error occurred. Details:
com.semmle.util.exception.CatastrophicError: An error occurred while evaluating DataFlowImpl::Impl<PartialPathTraversalQuery::PartialPathTraversalFromRemoteFlow::C>::Stage2::fwdFlowRetFromArg/10#07d045a9#reorder_2_3_4_5_0_1_6_7_8_9/10@i46#0ae342wa
com.semmle.util.exception.CatastrophicError: Could not load page 0 of DataFlowImplCommon::Cached::allowParameterReturnInSelfCached/1#79e1f2b4/1@f119e8ge (0e9e372sij60uvl1dnprq7isi811i)
The RA to evaluate was:

    {9} r1 = SCAN `DataFlowImpl::Impl<PartialPathTraversalQuery::PartialPathTraversalFromRemoteFlow::C>::Stage2::fwdFlow/9#c7184f54#prev_delta` OUTPUT In.2, In.0, In.1, In.3, In.4, In.5, In.6, In.7, In.8
    {9}    | JOIN WITH `DataFlowImplCommon::Cached::CachedCallContextSensitivity::instanceofCcCall/1#0f312245` ON FIRST 1 OUTPUT Lhs.3, Lhs.2, Lhs.0, Lhs.4, Lhs.5, Lhs.6, Lhs.7, Lhs.8, Lhs.1
    {9}    | JOIN WITH DataFlowImplCommon::Cached::TParamNodeSome#90847496_10#join_rhs ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2, Lhs.3, Lhs.4, Lhs.5, Lhs.6, Lhs.7, Lhs.8
    {9}    | JOIN WITH `num#DataFlowImpl::Impl<PartialPathTraversalQuery::PartialPathTraversalFromRemoteFlow::C>::TNodeNormal#8b88b606` ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2, Lhs.3, Lhs.4, Lhs.5, Lhs.6, Lhs.7, Lhs.8

    {10} r2 = JOIN r1 WITH `DataFlowImpl::Impl<PartialPathTraversalQuery::PartialPathTraversalFromRemoteFlow::C>::ParamNodeEx.isParameterOf/2#dispred#5d3eac0b` ON FIRST 1 OUTPUT Lhs.4, Lhs.1, Lhs.2, Lhs.3, Lhs.5, Lhs.6, Lhs.7, Lhs.8, Lhs.0, Rhs.2
    {10}    | JOIN WITH `DataFlowImpl::Impl<PartialPathTraversalQuery::PartialPathTraversalFromRemoteFlow::C>::Stage2Param::apSome/1#722f6f40_10#join_rhs` ON FIRST 1 OUTPUT Lhs.3, Lhs.1, Lhs.2, Lhs.4, Lhs.5, Lhs.6, Lhs.7, Lhs.8, Lhs.9, Rhs.1
    {11}    | JOIN WITH `num#Option::Option<Unit::Unit>::TSome#05f19f77_10#join_rhs` ON FIRST 1 OUTPUT Lhs.2, Lhs.7, Rhs.1, Lhs.9, Lhs.6, Lhs.1, Lhs.5, Lhs.3, Lhs.4, Lhs.5, Lhs.8
    {11}    | AND NOT `DataFlowImpl::Impl<PartialPathTraversalQuery::PartialPathTraversalFromRemoteFlow::C>::Stage2::fwdFlowRetFromArg/10#07d045a9#reorder_2_3_4_5_0_1_6_7_8_9#prev`(FIRST 10)
    {12}    | SCAN OUTPUT In.4, In.9, In.9, In.5, In.0, In.7, In.8, In.1, In.10, In.3, In.2, In.9
    {12}    | JOIN WITH `DataFlowImpl::Impl<PartialPathTraversalQuery::PartialPathTraversalFromRemoteFlow::C>::Stage1::returnMayFlowThrough/4#ac758084` ON FIRST 3 OUTPUT Lhs.8, Rhs.3, Lhs.3, Lhs.4, Lhs.5, Lhs.6, Lhs.0, Lhs.7, Lhs.9, Lhs.10, Lhs.1, Lhs.11
    {12}    | AND NOT DataFlowImplCommon::Cached::TParamUpdate#049ccdb9(FIRST 2)
    {11}    | SCAN OUTPUT In.6, In.1, In.2, In.3, In.4, In.5, In.7, In.8, In.9, In.10, In.11

    {9} r3 = JOIN r1 WITH `DataFlowImpl::Impl<PartialPathTraversalQuery::PartialPathTraversalFromRemoteFlow::C>::ParamNodeEx.isParameterOf/2#dispred#5d3eac0b` ON FIRST 1 OUTPUT Lhs.4, Lhs.1, Lhs.2, Lhs.3, Lhs.5, Lhs.6, Lhs.7, Lhs.8, Lhs.0
    {9}    | JOIN WITH `DataFlowImpl::Impl<PartialPathTraversalQuery::PartialPathTraversalFromRemoteFlow::C>::Stage2Param::apSome/1#722f6f40_10#join_rhs` ON FIRST 1 OUTPUT Lhs.3, Lhs.1, Lhs.2, Lhs.4, Lhs.5, Lhs.6, Lhs.7, Lhs.8, Rhs.1
    {10}    | JOIN WITH `num#Option::Option<Unit::Unit>::TSome#05f19f77_10#join_rhs` ON FIRST 1 OUTPUT Lhs.2, Lhs.7, Rhs.1, Lhs.8, Lhs.6, Lhs.1, Lhs.5, Lhs.3, Lhs.4, Lhs.5
    {10}    | AND NOT `DataFlowImpl::Impl<PartialPathTraversalQuery::PartialPathTraversalFromRemoteFlow::C>::Stage2::fwdFlowRetFromArg/10#07d045a9#reorder_2_3_4_5_0_1_6_7_8_9#prev`(FIRST 10)
    {11}    | SCAN OUTPUT In.4, In.9, In.9, In.5, In.0, In.7, In.8, In.1, In.3, In.2, In.9
    {11}    | JOIN WITH `DataFlowImpl::Impl<PartialPathTraversalQuery::PartialPathTraversalFromRemoteFlow::C>::Stage1::returnMayFlowThrough/4#ac758084` ON FIRST 3 OUTPUT Lhs.7, Lhs.3, Lhs.4, Lhs.5, Lhs.6, Lhs.0, Lhs.8, Lhs.9, Lhs.1, Lhs.10, Rhs.3
    {12}    | JOIN WITH `num#DataFlowImpl::Impl<PartialPathTraversalQuery::PartialPathTraversalFromRemoteFlow::C>::TNodeNormal#8b88b606_10#join_rhs` ON FIRST 1 OUTPUT Rhs.1, Lhs.1, Lhs.2, Lhs.3, Lhs.4, Lhs.5, Lhs.0, Lhs.6, Lhs.7, Lhs.8, Lhs.9, Lhs.10
    {11}    | JOIN WITH `DataFlowImplCommon::Cached::allowParameterReturnInSelfCached/1#79e1f2b4` ON FIRST 1 OUTPUT Lhs.5, Lhs.11, Lhs.1, Lhs.2, Lhs.3, Lhs.4, Lhs.6, Lhs.7, Lhs.8, Lhs.9, Lhs.10

    {11} r4 = r2 UNION r3
    {10}    | JOIN WITH `DataFlowImpl::Impl<PartialPathTraversalQuery::PartialPathTraversalFromRemoteFlow::C>::RetNodeEx.getKind/0#dispred#21cc3118` ON FIRST 2 OUTPUT Lhs.3, Lhs.6, Lhs.8, Lhs.7, Lhs.0, Lhs.2, Lhs.9, Lhs.4, Lhs.5, Lhs.10
    return r4

(eventual cause: CatastrophicError "Could not load page 0 of DataFlowImplCommon::Cached::allowParameterReturnInSelfC...")
	at com.semmle.inmemory.pipeline.PipelineInstance.wrapWithRaDump(PipelineInstance.java:168)
	at com.semmle.inmemory.pipeline.PipelineInstance.exceptionCaught(PipelineInstance.java:152)
	at com.semmle.inmemory.scheduler.execution.ThreadableWork.handleAndLog(ThreadableWork.java:593)
	at com.semmle.inmemory.scheduler.execution.ThreadableWork.doSomeWork(ThreadableWork.java:410)
	at com.semmle.inmemory.scheduler.RecursiveLayer$RecursiveWork.doWork(RecursiveLayer.java:330)
	at com.semmle.inmemory.scheduler.execution.ThreadableWork.doSomeWork(ThreadableWork.java:396)
	at com.semmle.inmemory.scheduler.execution.ExecutionScheduler.runnerMain(ExecutionScheduler.java:677)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.semmle.util.exception.CatastrophicError: Could not load page 0 of DataFlowImplCommon::Cached::allowParameterReturnInSelfCached/1#79e1f2b4/1@f119e8ge (0e9e372sij60uvl1dnprq7isi811i)
	at com.semmle.inmemory.caching.PagedRelation.getPage(PagedRelation.java:97)
	at com.semmle.inmemory.caching.PagedRelation.createMatcher(PagedRelation.java:132)
	at com.semmle.inmemory.pipeline.SetOpStep$SetOpState.processBatch(SetOpStep.java:63)
	at com.semmle.inmemory.pipeline.SimpleStep$SimpleState.deliverBatch(SimpleStep.java:146)
	at com.semmle.inmemory.pipeline.TupleCountingStep$TupleCountingState.processBatch(TupleCountingStep.java:114)
	at com.semmle.inmemory.pipeline.SimpleStep$SimpleState.doFlushingWork(SimpleStep.java:161)
	at com.semmle.inmemory.pipeline.PipelineState.doSomeWork(PipelineState.java:99)
	at com.semmle.inmemory.pipeline.PipelineInstance.doWork(PipelineInstance.java:117)
	at com.semmle.inmemory.scheduler.execution.ThreadableWork.doSomeWork(ThreadableWork.java:396)
	... 6 more

Database Analysis Failed
```

I'm not sure if what I'm doing is wrong (i.e : reusing the same db with different analysis) , do I need to run a database cleanup or is there a flag I can use to discard caching (other than what I'm already using). 

PS : This is happening only on large databases, the smaller one succeed with the two bundles (1) and (2)

**Comment by chmodxxx** [comment]
FWIW retrying analysis seems to solve this issue, but just wanted to share for SA. 
It's been consistently reproducing on a database and 1/2 on another, but retrying the same command works after failure

**Comment by smowton** [comment]
If it really is the same DB this sounds like an issue with the save/restore process. Can you verify the whole database directory is byte-for-byte the same before and after the restore operation?

**Comment by hmakholm** [comment]
We have fixed a bug in the cache management subsystem of the QL evaluator that was almost surely the cause of this symptom. The fix ought to be included in the next release of the CodeQL CLI.
