### ISSUE TITLE
When I use CodeQL to create a Csharp Database

### ISSUE THREAD

**Issue by wwwjwww** [github/codeql#17085]
**Description of the issue**
When I use codeql database create to create a database, it occurs error like:
JDK: 17.0.8.1
JDK Location:C:\Program Files (x86)\codeql\tools\win64\java
OS: Windows 10 10.0 amd64
 Details:
java.lang.NoClassDefFoundError: com/semmle/inmemory/caching/PagedRelation
	at com.semmle.inmemory.caching.Pager.<clinit>(Pager.java:34)
	at com.semmle.inmemory.scheduler.EvaluationSchedule.<init>(EvaluationSchedule.java:97)
	at com.semmle.inmemory.caching.RelationManager.<init>(RelationManager.java:68)
	at com.semmle.inmemory.MemoryBackend.<init>(MemoryBackend.java:132)
	at com.semmle.inmemory.trap.TrapImporter.<init>(TrapImporter.java:67)
	at com.semmle.cli2.ql.dataset.ImportCommand.executeSubcommand(ImportCommand.java:126)
	at com.semmle.cli2.picocli.SubcommandCommon.lambda$executeSubcommandWithMessages$5(SubcommandCommon.java:803)
	at com.semmle.cli2.picocli.SubcommandCommon.withCompilationMessages(SubcommandCommon.java:442)
	at com.semmle.cli2.picocli.SubcommandCommon.executeSubcommandWithMessages(SubcommandCommon.java:801)
	at com.semmle.cli2.picocli.PlumbingRunner.run(PlumbingRunner.java:119)
	at com.semmle.cli2.picocli.SubcommandCommon.runPlumbingInProcess(SubcommandCommon.java:199)
	at com.semmle.cli2.database.FinalizeCommand.doTrapImport(FinalizeCommand.java:249)
	at com.semmle.cli2.database.FinalizeCommand.finalizeOne(FinalizeCommand.java:190)
	at com.semmle.cli2.database.FinalizeCommand.executeSubcommand(FinalizeCommand.java:121)
	at com.semmle.cli2.picocli.SubcommandCommon.lambda$executeSubcommandWithMessages$5(SubcommandCommon.java:803)
	at com.semmle.cli2.picocli.SubcommandCommon.withCompilationMessages(SubcommandCommon.java:442)
	at com.semmle.cli2.picocli.SubcommandCommon.executeSubcommandWithMessages(SubcommandCommon.java:801)
	at com.semmle.cli2.picocli.PlumbingRunner.run(PlumbingRunner.java:119)
	at com.semmle.cli2.picocli.SubcommandCommon.runPlumbingInProcess(SubcommandCommon.java:199)
	at com.semmle.cli2.database.CreateCommand.executeSubcommand(CreateCommand.java:199)
	at com.semmle.cli2.picocli.SubcommandCommon.lambda$executeSubcommandWithMessages$5(SubcommandCommon.java:803)
	at com.semmle.cli2.picocli.SubcommandCommon.withCompilationMessages(SubcommandCommon.java:442)
	at com.semmle.cli2.picocli.SubcommandCommon.executeSubcommandWithMessages(SubcommandCommon.java:801)
	at com.semmle.cli2.picocli.SubcommandCommon.toplevelMain(SubcommandCommon.java:685)
	at com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:666)
	at com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:237)
	at com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:257)
	at com.semmle.cli2.CodeQL.main(CodeQL.java:115)

CodeQL-cli version: 2.16.3

**Comment by wwwjwww** [comment]
Fixed by downloading codeql-cli again. Thanks anyway.
