### ISSUE TITLE
CodeQL CLI linux UID error

### ISSUE THREAD

**Issue by knewbury01** [github/codeql#17859]
**Description of the issue**

CodeQL CLI 2.15.1 usage on linux

There appears to be a bug in the/(usage of?) `org.apache.commons.compress.archivers.tar.TarArchiveOutputStream` library (which the CodeQL CLI uses for tar'ing packs)

an error occurs with the following command: `codeql pack bundle --format=json --pack-path=codeql/qlpacks -- <path to custom packs>`

error log:
```
CRITICAL: Failed executing CodeQL command with reason: 'Failed to run ['<some-path>/codeql', 'pack', 'bundle', '--format=json', '--pack-path=<some-path>/codeql/qlpacks', '--', '<some-path-to-cusom-packs>'] command! Bundling <custom-packs>...
Collecting list of files to include in package.
Oops! A fatal internal error occurred. Details:
java.lang.IllegalArgumentException: user id '8692025' is too big ( > 2097151 ).
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:385)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:380)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(TarArchiveOutputStream.java:394)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:555)
	at com.semmle.cli2.pack.PackageArchive.saveArchiveForPack(PackageArchive.java:105)
	at com.semmle.cli2.pack.PackageManager.createPackageArchive(PackageManager.java:288)
	at com.semmle.cli2.pack.PackBundleCommand.executeJSON(PackBundleCommand.java:125)
	at com.semmle.cli2.pack.PackBundleCommand.executeJSON(PackBundleCommand.java:28)
	at com.semmle.cli2.picocli.SimpleJsonSubcommand.executeInsistingOnJSONWithExistingMessages(SimpleJsonSubcommand.java:133)
	at com.semmle.cli2.picocli.SimpleJsonSubcommand.executeSubcommand(SimpleJsonSubcommand.java:82)
	at com.semmle.cli2.picocli.SubcommandCommon.lambda$executeSubcommandWithMessages$5(SubcommandCommon.java:863)
	at com.semmle.cli2.picocli.SubcommandCommon.withCompilationMessages(SubcommandCommon.java:442)
	at com.semmle.cli2.picocli.SubcommandCommon.executeSubcommandWithMessages(SubcommandCommon.java:861)
	at com.semmle.cli2.picocli.SubcommandCommon.toplevelMain(SubcommandCommon.java:745)
	at com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:726)
	at com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:237)
	at com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:257)
	at com.semmle.cli2.CodeQL.main(CodeQL.java:115)
```
appears to be the same issue as [#4384 user id 'xxx' is too big ( > 2097151 ) when using commons-compress 1.21 with large user ID](https://github.com/testcontainers/testcontainers-java/issues/4384) - **includes suggestion for which lib setting flag to add to fix this**

**Comment by knewbury01** [comment]
expecting this to be fixed in [this PR](https://github.com/github/semmle-code/pull/51808/files)

**Comment by knewbury01** [comment]
confirmed fixed in 2.19.4
