### ISSUE TITLE
 The TypeScript parser wrapper crashed with exit code 1

### ISSUE THREAD

**Issue by keysenYang** [github/codeql#17862]
```
D:\yqs\appdata\CodeQL\databases\javascript\product>codeql database create --overwrite --language=typescript --source-root D:\yqs\appdata\CodeQL\source\javascript\test-ts D:\test-ts-db
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Initializing database at D:\test-ts-db.
Running build command: []
Running command in D:\yqs\appdata\CodeQL\source\javascript\test-ts: [D:\Program Files\CodeQL\codeql\javascript\tools\autobuild.cmd]
[2024-10-29 16:02:59] [build-stderr] Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
[2024-10-29 16:02:59] [build-stdout] Single-threaded extraction.
[2024-10-29 16:02:59] [build-stdout] Found Node.js at: node
[2024-10-29 16:02:59] [build-stdout] Found Node.js version: v12.18.2
[2024-10-29 16:02:59] [build-stdout] Memory for TypeScript process: 2000 MB, and 400 MB reserve
[2024-10-29 16:03:00] [build-stderr] D:\Program Files\CodeQL\codeql\javascript\tools\typescript-parser-wrapper\node_modules\typescript\lib\typescript.js:2469
[2024-10-29 16:03:00] [build-stderr]   for (let i = startIndex ?? 0; i < array.length; i++) {
[2024-10-29 16:03:00] [build-stderr]                            ^
[2024-10-29 16:03:00] [build-stderr] SyntaxError: Unexpected token '?'
[2024-10-29 16:03:00] [build-stderr]     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
[2024-10-29 16:03:00] [build-stderr]     at Module._compile (internal/modules/cjs/loader.js:1102:27)
[2024-10-29 16:03:00] [build-stderr]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
[2024-10-29 16:03:00] [build-stderr]     at Module.load (internal/modules/cjs/loader.js:986:32)
[2024-10-29 16:03:00] [build-stderr]     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
[2024-10-29 16:03:00] [build-stderr]     at Module.require (internal/modules/cjs/loader.js:1026:19)
[2024-10-29 16:03:00] [build-stderr]     at require (internal/modules/cjs/helpers.js:72:18)
[2024-10-29 16:03:00] [build-stderr]     at Object.<anonymous> (D:\Program Files\CodeQL\codeql\javascript\tools\typescript-parser-wrapper\typescript.js:6:22)
[2024-10-29 16:03:00] [build-stderr]     at Module._compile (internal/modules/cjs/loader.js:1138:30)
[2024-10-29 16:03:00] [build-stderr]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
[2024-10-29 16:03:00] [build-stderr] com.semmle.util.exception.CatastrophicError: The TypeScript parser wrapper crashed with exit code 1
[2024-10-29 16:03:00] [build-stderr]    at com.semmle.ts.extractor.TypeScriptParser.getExceptionFromMalformedResponse(TypeScriptParser.java:399)
[2024-10-29 16:03:00] [build-stderr]    at com.semmle.ts.extractor.TypeScriptParser.talkToParserWrapper(TypeScriptParser.java:364)
[2024-10-29 16:03:00] [build-stderr]    at com.semmle.ts.extractor.TypeScriptParser.loadMetadata(TypeScriptParser.java:416)
[2024-10-29 16:03:00] [build-stderr]    at com.semmle.ts.extractor.TypeScriptParser.setupParserWrapper(TypeScriptParser.java:320)
[2024-10-29 16:03:00] [build-stderr]    at com.semmle.ts.extractor.TypeScriptParser.talkToParserWrapper(TypeScriptParser.java:351)
[2024-10-29 16:03:00] [build-stderr]    at com.semmle.ts.extractor.TypeScriptParser.prepareFiles(TypeScriptParser.java:462)
[2024-10-29 16:03:00] [build-stderr]    at com.semmle.js.extractor.AutoBuild.extractTypeScriptFiles(AutoBuild.java:1191)
[2024-10-29 16:03:00] [build-stderr]    at com.semmle.js.extractor.AutoBuild.extractTypeScript(AutoBuild.java:1091)
[2024-10-29 16:03:00] [build-stderr]    at com.semmle.js.extractor.AutoBuild.extractSource(AutoBuild.java:758)
[2024-10-29 16:03:00] [build-stderr]    at com.semmle.js.extractor.AutoBuild.run(AutoBuild.java:464)
[2024-10-29 16:03:00] [build-stderr]    at com.semmle.js.extractor.AutoBuild.main(AutoBuild.java:1360)
[2024-10-29 16:03:00] [ERROR] Spawned process exited abnormally (code 1; tried to run: [D:\Program Files\CodeQL\codeql\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, D:\Program Files\CodeQL\codeql\javascript\tools\autobuild.cmd])
A fatal error occurred: Exit status 1 from command: [D:\Program Files\CodeQL\codeql\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, D:\Program Files\CodeQL\codeql\javascript\tools\autobuild.cmd]
```

**Comment by mbg** [comment]
Hi @keysenYang 👋🏻 

Thanks for the report. Could you confirm which version of CodeQL you are using?

I just tried to replicate your problem with a recent version of CodeQL and `codeql database create` was able to succeed for a file containing `for (let i = startIndex ?? 0; i < array.length; i++) {`

**Comment by erik-krogh** [comment]
I think the problem is that your NodeJS version is old.  

See this line in the logs: 
```
[2024-10-29 16:02:59] [build-stdout] Found Node.js version: v12.18.2
```

I think we require at least Node 16. (It's documented somewhere).

**Comment by keysenYang** [comment]
Yes, the problem is my NodeJS version is old. I changed nodejs to 16.5.0 and the problem was solved.
