### ISSUE TITLE
Add support for JDK 15

### ISSUE THREAD

**Issue by Thihup** [github/codeql#4281]
**Description of the issue**
We've recently changed our build to use JDK 15. However, the CodeQL reports it cannot find any source [1].
Looking in the logs, there is an exception at the start of the build [2]. 
As far as I can tell, there is a Java agent that read classes, but it doesn't support JDK 15.

[1]
```
/opt/hostedtoolcache/CodeQL/0.0.0-20200826/x64/codeql/codeql database finalize /home/runner/work/_temp/codeql_databases/java
  No source code was seen during the build.
  This can occur if the specified build commands failed to compile or process any code.
   - Confirm that there is some source code for the specified language in the project.
   - For codebases written in Go, JavaScript, TypeScript, and Python, do not specify 
     an explicit --command.
   - For other languages, the --command must specify a "clean" build which compiles 
     all the source code files without reusing existing build artefacts.
  ##[error]The process '/opt/hostedtoolcache/CodeQL/0.0.0-20200826/x64/codeql/codeql' failed with exit code 32
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20200826/x64/codeql/codeql' failed with exit code 32
      at ExecState._setResult (/home/runner/work/_actions/github/codeql-action/v1/node_modules/@actions/exec/lib/toolrunner.js:548:25)
      at ExecState.CheckComplete (/home/runner/work/_actions/github/codeql-action/v1/node_modules/@actions/exec/lib/toolrunner.js:531:18)
      at ChildProcess.<anonymous> (/home/runner/work/_actions/github/codeql-action/v1/node_modules/@actions/exec/lib/toolrunner.js:431:27)
      at ChildProcess.emit (events.js:210:5)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```
[2]
```
java.lang.IllegalArgumentException: Unsupported class file major version 59
	at com.semmle.org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
	at com.semmle.org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
	at com.semmle.org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
	at com.semmle.extractor.java.InterceptingAgent.transform(InterceptingAgent.java:262)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ApplicationShutdownHooks.<clinit>(ApplicationShutdownHooks.java:42)
	at java.base/java.lang.Runtime.addShutdownHook(Runtime.java:215)
	at org.apache.maven.shared.utils.logging.MessageUtils.registerShutdownHook(MessageUtils.java:201)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by aibaars** [comment]
Wow, that's quick. Switching to a new Java version 2 days after the "General Availability" release. :1st_place_medal: 

You're right though, we should update the agent and source code analyzer to work for Java 15.

**Comment by krusche** [comment]
We experience a similar issue. Would be great if Java15 could be supported

**Comment by gjvoosten** [comment]
@aibaars @aschackmull @Thihup I guess this is no longer a **question** but some serious debt (some might even say bug). Two months on and still no progress?

**Comment by Thihup** [comment]
We gave up using CodeQL for now, unfortunately

**Comment by gjvoosten** [comment]
Could you at least remove the **question* label (and perhaps replace it with **bug**), for the benefit of others who (like me) *are* still using CodeQL. @Thihup ?

**Comment by Thihup** [comment]
I guess I cannot do that... Actually, I don't know how it got the _Question_ label

**Comment by sj** [comment]
Hi folks! Thanks for chasing this. I completely understand this is frustrating, and it's something we're working hard on to resolve. I (or one of my colleagues) will post a more detailed update tomorrow at the latest!

**Comment by sj** [comment]
As promised: an update with a few more details!

For every new language version, it's a multi-step process to develop CodeQL support:
 1. Make sure the CodeQL extractor recognises the new compiler version. That includes making sure that the extractor understand any changes to the compiler's behaviour (in this case: `javac` version 15). That includes cases in which the compiler operates on a code base that does not use any new Java language features.
 2. Make sure the CodeQL extractor extracts new Java 15 language features into the CodeQL database.
 3. Update the CodeQL queries to actually incorporate the new language features when performing analysis on the CodeQL database.

We're currently testing a draft PR that addresses (1), and things are looking good :slightly_smiling_face:. Once that's been merged and deployed, things should work for most codebases. We'll keep you posted on when we expect to deploy this!

**Comment by sj** [comment]
The first improvements have landed on the default CodeQL engine version that runs inside GitHub code scanning. This means that using Java 15 `javac` to build your code should no longer cause any issues. Let me know if you still encounter any problems!

**Comment by gjvoosten** [comment]
I can confirm that our Java 15 builds can now run the CodeQL GitHub Action successfully. :+1:
