### ISSUE TITLE
Android: Throw an OutOfMemoryError when creating a database

### ISSUE THREAD

**Issue by LqL670** [github/codeql#5292]
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at javac_extend.com.sun.tools.javac.code.Scope$ScopeImpl.dupUnshared(Scope.java:377)
	at javac_extend.com.sun.tools.javac.comp.MemberEnter.initEnv(MemberEnter.java:425)
	at javac_extend.com.sun.tools.javac.comp.MemberEnter.getInitEnv(MemberEnter.java:454)
	at javac_extend.com.sun.tools.javac.comp.MemberEnter.visitVarDef(MemberEnter.java:295)
	at javac_extend.com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:993)
	at javac_extend.com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:164)
	at javac_extend.com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:176)
	at javac_extend.com.sun.tools.javac.comp.TypeEnter$MembersPhase.finishClass(TypeEnter.java:1081)
	at javac_extend.com.sun.tools.javac.comp.TypeEnter$MembersPhase.runPhase(TypeEnter.java:1025)
	at javac_extend.com.sun.tools.javac.comp.TypeEnter$Phase.doCompleteEnvs(TypeEnter.java:292)
	at javac_extend.com.sun.tools.javac.comp.TypeEnter$AbstractMembersPhase.doCompleteEnvs(TypeEnter.java:935)
	at javac_extend.com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:261)
	at javac_extend.com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:276)
	at javac_extend.com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:276)
	at javac_extend.com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:276)
	at javac_extend.com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:276)
	at javac_extend.com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:276)
	at javac_extend.com.sun.tools.javac.comp.TypeEnter.complete(TypeEnter.java:208)
	at javac_extend.com.sun.tools.javac.code.Symbol.complete(Symbol.java:685)
	at javac_extend.com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1413)
	at javac_extend.com.sun.tools.javac.comp.Enter.complete(Enter.java:584)
	at javac_extend.com.sun.tools.javac.comp.Enter.main(Enter.java:561)
	at javac_extend.com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:1069)
	at com.semmle.extractor.java.JavaExtractor.runExtractor(JavaExtractor.java:289)
	at com.semmle.extractor.java.JavaExtractor.runExtractor(JavaExtractor.java:223)
	at com.semmle.extractor.java.JavaExtractor.main(JavaExtractor.java:487)
[Process Builder] Spawned process exited abnormally (code 1; tried to run: [/Users/aaa/work/codeql-home/codeql/java/tools/macos/jdk-extractor-java/bin/java, -Dfile.encoding=UTF-8, -Xmx1024M, -Xms256M, -classpath, /Users/aaa/work/codeql-home/codeql/java/tools/semmle-extractor-java.jar, com.semmle.extractor.java.JavaExtractor, --jdk-version, -1, --javac-args, @@@/Users/aaa/work/a/b/java-databse/log/ext/javac-5.args]
[ODASA Javac] Non-zero exit code 1 from ODASA javac builder
> Task :app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac took 45592ms
> Task :app:compileDebugJavaWithJavac FAILED
```

**Comment by LqL670** [comment]
I think it may be that -Xmx1024M is set too small, how can I set a larger value?

**Comment by aeisenberg** [comment]
A little surprised that the default is too small for you. It is possible to explicitly set options directly sent to the underlying JVM. You can do this by using a `-J=` prefix. To set 2GB for the heap, you can:

```
codeql create database -J=-Xmx2G -J=-Xms1G ...`
```

**Comment by LqL670** [comment]
It doesn't work.I found the above hard-coded -Xmx1024M code.  @aeisenberg 
com.semmle.extractor.java.Utils.invokeOdasaJavac  in codeql-java-agent.jar

`ArrayList cmdLine = new ArrayList(Arrays.asList(new String[]{runExtractorJDK + File.separator + "bin" + File.separator + executable, "-Dfile.encoding=UTF-8", "-Xmx1024M", "-Xms256M"}));`

**Comment by LqL670** [comment]
Analyzing the log, I think the problem is that the hard-coded value here is too small, what do you think?

**Comment by aeisenberg** [comment]
That seems like a plausible explanation. Two things I can recommend trying:

1. Try explicitly setting a [compile command](https://codeql.github.com/docs/codeql-cli/creating-codeql-databases/#specifying-build-commands), like `codeql database create --command="javac -Xmx2G ..." ...`
2. You can specify extra JVM arguments in the `SEMMLE_JAVA_EXTRACTOR_JVM_ARGS` environment variable.

If neither of those help, I'll get someone with more direct experience on the extractor to weigh in.

**Comment by LqL670** [comment]
Thanks for your answer.I specify extra JVM arguments in the SEMMLE_JAVA_EXTRACTOR_JVM_ARGS，like `export SEMMLE_JAVA_EXTRACTOR_JVM_ARGS='-Xmx4g -Xms512m'`Finally, there was no problem.
