### ISSUE TITLE
Python: Error creating DB with old version of `idna/idnadata`

### ISSUE THREAD

**Issue by thepurpleowl** [github/codeql#5807]
Similar issue #4496

Following are my setup details:
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
Python: 3.5.6
Codeql: CodeQL command-line toolchain release 2.5.0
Codeql repo commit: 4d2db089342802ae82e217cf9decee73c414768c

Command: codeql database create --language=python --source-root=<src_dir> <db_name>

Log:
```
[2021-04-29 16:33:31] [build-stdout] [INFO] [9] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/s3fs/errors.py in 321ms    

[2021-04-29 16:33:31] [build-stdout] [INFO] [3] Extracted file /home/sps/data-analysis/train_ind_data/py_file_31327.py in 781ms    
[2021-04-29 16:33:31] [build-stdout] [INFO] [3] Extracted folder /home/sps/anaconda3/lib/python3.5/site-packages/pathlib2 in 1ms      
[2021-04-29 16:33:31] [build-stdout] [INFO] [2] Extracted file /home/sps/data-analysis/train_ind_data/py_file_38346.py in 196ms    
[2021-04-29 16:33:31] [build-stdout] [INFO] [15] Extracted file /home/sps/data-analysis/train_ind_data/py_file_51056.py in   \\\1035ms  
[2021-04-29 16:33:31] [build-stdout] [INFO] [2] Extracted file /home/sps/data-analysis/train_ind_data/py_file_33997.py in 98ms  
[2021-04-29 16:33:32] [build-stdout] [ERROR] [5] Failed to extract file /home/sps/anaconda3/lib/python3.5/site-packages/idna/idnadata.py: maximum recursion d
epth exceeded while calling a Python object
[2021-04-29 16:33:32] [build-stdout] [TRACEBACK] [5] "semmle/python/passes/ast_pass.py", line 208, in visit
[2021-04-29 16:33:32] [build-stdout] [TRACEBACK] [5] "semmle/python/passes/ast_pass.py", line 213, in generic_visit
[2021-04-29 16:33:32] [build-stdout] [TRACEBACK] [5] "semmle/python/passes/ast_pass.py", line 208, in visit
[2021-04-29 16:33:32] [build-stdout] [TRACEBACK] [5] "semmle/python/passes/ast_pass.py", line 212, in generic_visit
[2021-04-29 16:33:32] [build-stdout] [TRACEBACK] [5] "semmle/python/passes/ast_pass.py", line 144, in iter_fields
[2021-04-29 16:33:32] [build-stdout] [INFO] [3] Extracted file /home/sps/data-analysis/train_ind_data/py_file_11600.py in 268ms
[2021-04-29 16:33:32] [build-stdout] [INFO] [15] Extracted file /home/sps/data-analysis/train_ind_data/py_file_62822.py in 186ms
[2021-04-29 16:33:32] [build-stdout] [INFO] [2] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/pywt/data/_readers.py in 102ms
[2021-04-29 16:33:32] [build-stdout] [INFO] [5] Extracted file /home/sps/data-analysis/train_ind_data/py_file_38035.py in 77ms
[2021-04-29 16:33:32] [build-stdout] [INFO] [9] Extracted file /home/sps/data-analysis/train_ind_data/py_file_64551.py in 515ms
[2021-04-29 16:33:32] [build-stdout] [INFO] [13] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/pandas/core/indexes/multi.py in 4590ms
[2021-04-29 16:33:32] [build-stdout] [INFO] [10] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/requests/packages/chardet/jpcntx.py in 3155ms
[2021-04-29 16:33:32] [build-stdout] [INFO] [6] Extracted file /home/sps/anaconda3/lib/python3.5/multiprocessing/synchronize.py in 648ms
[2021-04-29 16:33:32] [build-stdout] [INFO] [8] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/requests/packages/chardet/langthaimodel.py in 
1818ms
[2021-04-29 16:33:32] [build-stdout] [INFO] [12] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/pywt/_wavelet_packets.py in 1037ms
[2021-04-29 16:33:32] [build-stdout] [INFO] [14] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/sympy/simplify/sqrtdenest.py in 1037ms
[2021-04-29 16:33:32] [build-stdout] [INFO] [4] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/dask/dataframe/io/parquet/arrow.py in 1074ms
[2021-04-29 16:33:32] [build-stdout] [INFO] [16] Extracted file /home/sps/data-analysis/train_ind_data/py_file_33618.py in 2805ms
[2021-04-29 16:33:34] [build-stdout] [ERROR] Process 1 timed out
[2021-04-29 16:33:34] [build-stdout] [ERROR] Process 7 timed out
[2021-04-29 16:33:34] [build-stdout] [ERROR] Process 11 timed out
[2021-04-29 16:33:38] [build-stderr] Traceback (most recent call last):
[2021-04-29 16:33:38] [build-stderr]   File "/home/sps/codeql-home/codeql/python/tools/index.py", line 22, in <module>
[2021-04-29 16:33:38] [build-stderr]     buildtools.index.main()
[2021-04-29 16:33:38] [build-stderr]   File "/home/sps/codeql-home/codeql/python/tools/python3src.zip/buildtools/index.py", line 110, in main
[2021-04-29 16:33:38] [build-stderr]   File "/home/sps/anaconda3/lib/python3.5/subprocess.py", line 271, in check_call
[2021-04-29 16:33:38] [build-stderr]     raise CalledProcessError(retcode, cmd)
[2021-04-29 16:33:38] [build-stderr] subprocess.CalledProcessError: Command '['python3', '-S', '/home/sps/codeql-home/codeql/python/tools/python_tracer.py', 
'-v', '-z', 'all', '-c', '/home/sps/data-analysis/train_ind_db/working/trap_cache', '-p', '/home/sps/anaconda3/lib/python3.5/site-packages', '-R', '
/home/sps/data-analysis/train_ind_data']' returned non-zero exit status 1
[2021-04-29 16:33:38] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/home/sps/codeql-home/codeql/python/tools/autobuild.sh])
A fatal error occurred: Exit status 1 from command: [/home/sps/codeql-home/codeql/python/tools/autobuild.sh][2021-04-29 16:33:31] [build-stdout] [INFO] [9] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/s3fs/errors.py in 321ms
[2021-04-29 16:33:31] [build-stdout] [INFO] [3] Extracted file /home/sps/data-analysis/train_ind_data/py_file_31327.py in 781ms
[2021-04-29 16:33:31] [build-stdout] [INFO] [3] Extracted folder /home/sps/anaconda3/lib/python3.5/site-packages/pathlib2 in 1ms
[2021-04-29 16:33:31] [build-stdout] [INFO] [2] Extracted file /home/sps/data-analysis/train_ind_data/py_file_38346.py in 196ms
[2021-04-29 16:33:31] [build-stdout] [INFO] [15] Extracted file /home/sps/data-analysis/train_ind_data/py_file_51056.py in 1035ms
[2021-04-29 16:33:31] [build-stdout] [INFO] [2] Extracted file /home/sps/data-analysis/train_ind_data/py_file_33997.py in 98ms
[2021-04-29 16:33:32] [build-stdout] [ERROR] [5] Failed to extract file /home/sps/anaconda3/lib/python3.5/site-packages/idna/idnadata.py: maximum recursion d
epth exceeded while calling a Python object
[2021-04-29 16:33:32] [build-stdout] [TRACEBACK] [5] "semmle/python/passes/ast_pass.py", line 208, in visit
[2021-04-29 16:33:32] [build-stdout] [TRACEBACK] [5] "semmle/python/passes/ast_pass.py", line 213, in generic_visit  
[2021-04-29 16:33:32] [build-stdout] [TRACEBACK] [5] "semmle/python/passes/ast_pass.py", line 208, in visit    
[2021-04-29 16:33:32] [build-stdout] [TRACEBACK] [5] "semmle/python/passes/ast_pass.py", line 212, in generic_visit  
[2021-04-29 16:33:32] [build-stdout] [TRACEBACK] [5] "semmle/python/passes/ast_pass.py", line 144, in iter_fields  
[2021-04-29 16:33:32] [build-stdout] [INFO] [3] Extracted file /home/sps/data-analysis/train_ind_data/py_file_11600.py in 268ms  
[2021-04-29 16:33:32] [build-stdout] [INFO] [15] Extracted file /home/sps/data-analysis/train_ind_data/py_file_62822.py in 186ms  
[2021-04-29 16:33:32] [build-stdout] [INFO] [2] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/pywt/data/_readers.py in 102ms  
[2021-04-29 16:33:32] [build-stdout] [INFO] [5] Extracted file /home/sps/data-analysis/train_ind_data/py_file_38035.py in 77ms  
[2021-04-29 16:33:32] [build-stdout] [INFO] [9] Extracted file /home/sps/data-analysis/train_ind_data/py_file_64551.py in 515ms  
[2021-04-29 16:33:32] [build-stdout] [INFO] [13] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/pandas/core/indexes/multi.py in 4590ms  
[2021-04-29 16:33:32] [build-stdout] [INFO] [10] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/requests/packages/chardet/jpcntx.py in 3155ms  
[2021-04-29 16:33:32] [build-stdout] [INFO] [6] Extracted file /home/sps/anaconda3/lib/python3.5/multiprocessing/synchronize.py in 648ms  
[2021-04-29 16:33:32] [build-stdout] [INFO] [8] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/requests/packages/chardet/langthaimodel.py in 
1818ms  
[2021-04-29 16:33:32] [build-stdout] [INFO] [12] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/pywt/_wavelet_packets.py in 1037ms  
[2021-04-29 16:33:32] [build-stdout] [INFO] [14] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/sympy/simplify/sqrtdenest.py in 1037ms  
[2021-04-29 16:33:32] [build-stdout] [INFO] [4] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/dask/dataframe/io/parquet/arrow.py in 1074ms  
[2021-04-29 16:33:32] [build-stdout] [INFO] [16] Extracted file /home/sps/data-analysis/train_ind_data/py_file_33618.py in 2805ms  
[2021-04-29 16:33:34] [build-stdout] [ERROR] Process 1 timed out  
[2021-04-29 16:33:34] [build-stdout] [ERROR] Process 7 timed out  
[2021-04-29 16:33:34] [build-stdout] [ERROR] Process 11 timed out  
[2021-04-29 16:33:38] [build-stderr] Traceback (most recent call last):
[2021-04-29 16:33:38] [build-stderr]   File "/home/sps/codeql-home/codeql/python/tools/index.py", line 22, in <module>
[2021-04-29 16:33:38] [build-stderr]     buildtools.index.main()
[2021-04-29 16:33:38] [build-stderr]   File "/home/sps/codeql-home/codeql/python/tools/python3src.zip/buildtools/index.py", line 110, in main
[2021-04-29 16:33:38] [build-stderr]   File "/home/sps/anaconda3/lib/python3.5/subprocess.py", line 271, in check_call
[2021-04-29 16:33:38] [build-stderr]     raise CalledProcessError(retcode, cmd)
[2021-04-29 16:33:38] [build-stderr] subprocess.CalledProcessError: Command '['python3', '-S', '/home/sps/codeql-home/codeql/python/tools/python_tracer.py', 
'-v', '-z', 'all', '-c', '/home/sps/data-analysis/train_ind_db/working/trap_cache', '-p', '/home/sps/anaconda3/lib/python3.5/site-packages', '-R', '  
/home/sps/data-analysis/train_ind_data']' returned non-zero exit status 1  
[2021-04-29 16:33:38] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/home/sps/codeql-home/codeql/python/tools/autobuild.sh])  
A fatal error occurred: Exit status 1 from command: [/home/sps/codeql-home/codeql/python/tools/autobuild.sh]
```

I am able to run the same command on the same data without any error with 
Ubuntu 18.04.5 LTS
Python: 3.8.5
Codeql: same version
Codeql repo commit: same hash

Also in both cases the created database size is same.

**Comment by RasmusWL** [comment]
Thanks for creating this separate report @thepurpleowl :+1:

The interesting bit from this log output is 

```
[2021-04-29 16:33:32] [build-stdout] [ERROR] [5] Failed to extract file /home/sps/anaconda3/lib/python3.5/site-packages/idna/idnadata.py: maximum recursion depth exceeded while calling a Python object
```

which makes it a very different problem than #4496.

I'll see if I can create a reproducible example.

**Comment by RasmusWL** [comment]
@thepurpleowl I've been able to reproduce when using `idna==2.0` (released in 2015), and I assume this will fail when using any of the previous versions.

As a work-around, can you try updating `idna` to a more recent version?

**Comment by thepurpleowl** [comment]
This error is still occurring with `idna==3.1`.

`[2021-05-03 20:50:50] [build-stdout] [ERROR] [11] Failed to extract file /home/sps/anaconda3/lib/python3.5/site-packages/idna/idnadata.py: maximum recursion depth exceeded while calling a Python object`

------------
But the difference is the `database create` is not exiting with error, seems to be stuck. Last few log lines as follows
```
[2021-05-03 20:50:50] [build-stdout] [INFO] [3] Extracted folder /home/sps/data-analysis/train_data/gregmuellegger/django-debug-toolbar-autoreload in 0ms   
[2021-05-03 20:50:50] [build-stdout] [INFO] [1] Extracted file /home/sps/data-analysis/train_data/miguelgrinberg/Flask-Migrate/tests/test_multidb_migrate.py
in 129ms
[2021-05-03 20:50:50] [build-stdout] [INFO] [2] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/numba/jitclass/base.py in 456ms              
[2021-05-03 20:50:50] [build-stdout] [INFO] [16] Extracted file /home/sps/data-analysis/train_data/upconsulting/IsisCB/isiscb/zotero/migrations/0001_initial.
py in 315ms
[2021-05-03 20:50:50] [build-stdout] [INFO] [10] Extracted file /home/sps/data-analysis/train_data/ottokart/punctuator/src/utils.py in 66ms                 
[2021-05-03 20:50:50] [build-stdout] [ERROR] [11] Failed to extract file /home/sps/anaconda3/lib/python3.5/site-packages/idna/idnadata.py: maximum recursion
depth exceeded while calling a Python object
[2021-05-03 20:50:50] [build-stdout] [TRACEBACK] [11] "semmle/python/passes/ast_pass.py", line 208, in visit                                                         
[2021-05-03 20:50:50] [build-stdout] [TRACEBACK] [11] "semmle/python/passes/ast_pass.py", line 213, in generic_visit                                                 
[2021-05-03 20:50:50] [build-stdout] [TRACEBACK] [11] "semmle/python/passes/ast_pass.py", line 208, in visit                                                         
[2021-05-03 20:50:50] [build-stdout] [TRACEBACK] [11] "semmle/python/passes/ast_pass.py", line 212, in generic_visit                                                 
[2021-05-03 20:50:50] [build-stdout] [TRACEBACK] [11] "semmle/python/passes/ast_pass.py", line 144, in iter_fields                                                   
[2021-05-03 20:50:50] [build-stdout] [INFO] [7] Extracted file /home/sps/data-analysis/train_data/biocore/scikit-bio/skbio/sequence/_sequence.py in 720ms   
[2021-05-03 20:50:50] [build-stdout] [INFO] [16] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/pandas/io/msgpack/exceptions.py in 50ms     
[2021-05-03 20:50:50] [build-stdout] [INFO] [11] Extracted file /home/sps/data-analysis/train_data/topazproject/topaz/topaz/objects/codeobject.py in 91ms   
[2021-05-03 20:50:50] [build-stdout] [INFO] [12] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/pip/_vendor/html5lib/html5parser.py in 3502ms
[2021-05-03 20:50:50] [build-stdout] [INFO] [14] Extracted file /home/sps/anaconda3/lib/python3.5/site-packages/scipy/cluster/__init__.py in 47ms           
[2021-05-03 20:50:50] [build-stdout] [INFO] [6] Extracted file /home/sps/data-analysis/train_data/jsirois/sapling/sapling.py in 368ms 
```

**Comment by RasmusWL** [comment]
@thepurpleowl that's very strange, using `idna==3.1` works fine on my end. Just to make sure, can you show the output from running `head /home/sps/anaconda3/lib/python3.5/site-packages/idna/idnadata.py`?

**Comment by thepurpleowl** [comment]
Yeah, updating seems to be working.

Closing.
