### ISSUE TITLE
CodeQL Analysis Error: codeql.exe fails with exit code 100

### ISSUE THREAD

**Issue by egorodet** [github/codeql#5968]
**Description of the issue**

CodeQL analysis has started failing with a huge 20000 lines debug output which finishes the following:

```
Scheduler is idle before completion of internal stage {139.16}FlowVar::FlowVar#class#f FlowVar::FlowVar::getAnAccess_dispred#ff FlowVar::FlowVar::definedPartiallyAt_dispred#ff FlowVar::FlowVar::definedByInitialValue_dispred#ff FlowVar::FlowVar::definedByExpr_dispred#fff FlowVar::FlowVar::toString_dispred#ff FlowVar::FlowVar::getLocation_dispred#ff FlowVar::FlowVar::reachesRefParameter_dispred#ff
  If you see this error in a production run with the latest CLI, please file a report including the above graph dump.
  	at com.semmle.inmemory.scheduler.EvaluationSchedule.throwErrorIncludingGraphDump(EvaluationSchedule.java:165)
  	at com.semmle.inmemory.scheduler.StageTask.lambda$evaluateAsync$1(StageTask.java:123)
  	at com.semmle.inmemory.scheduler.ExecutionScheduler$IdleNotifier.trigger(ExecutionScheduler.java:724)
  	at java.base/java.lang.Iterable.forEach(Unknown Source)
  	at com.semmle.inmemory.scheduler.ExecutionScheduler.checkIdle(ExecutionScheduler.java:694)
  	at com.semmle.inmemory.scheduler.ExecutionScheduler.finishRunner(ExecutionScheduler.java:617)
  	at com.semmle.inmemory.scheduler.ExecutionScheduler.runnerMain(ExecutionScheduler.java:575)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  	at java.base/java.lang.Thread.run(Unknown Source)
  Error: The process 'C:\hostedtoolcache\windows\CodeQL\0.0.0-20210503\x64\codeql\codeql.exe' failed with exit code 100
  Error: Error running analysis for cpp: Error: The process 'C:\hostedtoolcache\windows\CodeQL\0.0.0-20210503\x64\codeql\codeql.exe' failed with exit code 100
  CodeQLAnalysisError: Error running analysis for cpp: Error: The process 'C:\hostedtoolcache\windows\CodeQL\0.0.0-20210503\x64\codeql\codeql.exe' failed with exit code 100
      at runQueries (D:\a\_actions\github\codeql-action\v1\lib\analyze.js:130:19)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    name: 'CodeQLAnalysisError',
    queriesStatusReport: { analyze_failure_language: 'cpp' }
```

- See full debug output of the CodeQL in MethaneKit actions: https://github.com/egorodet/MethaneKit/runs/2694745896?check_suite_focus=true
- See attached log of the CodeQL failure: [CodeQL-Failure-Log.txt](https://github.com/github/codeql/files/6561977/CodeQL-Failure-Log.txt)
- Note that CodeQL fails on Windows only, while Linux and MacOS checks are running fine. Previous commits were passing CodeQL checks on all platforms successfully.

**Comment by alexet** [comment]
Thanks for the bug report. We will look into fixing this.

Rerunning may make the issue go away if you are blocked by this failure.

**Comment by egorodet** [comment]
I've already tried rerunning jobs, but it failed again.

**Comment by hmakholm** [comment]
Ouch. That's a strange failure mode, and even stranger if it's reproducible. How I wish the action gave us a way to get at the internal log rather than just the stdout output.

----

_Internal troubleshooting thing-aloud:_

The incriminating part of the huge graph dump appears to be this:
```
  cacher {138}SSAUtils::SSAHelper::toString_dispred#ffff/4@b6cc3d
      needs /\ /\ with NOT_YET
      needs cacher {138}Declaration::Declaration::getName_dispred#ff/2@e4e0c4 with NOT_YET
    | FRESH, demand NOT_YET
    used by \/ \/ with NOT_YET
  computed extensional evaluator {138}SSAUtils::SSAHelper::toString_dispred#ffff/4@a6f3bc
      needs /\ /\ with NOT_YET
    | ABANDONED, demand {140.13}RELATION.139002
    used by \/ \/ with {140.13}RELATION.139002
  cacher {138}SSAUtils::SSAHelper::toString_dispred#ffff/4@a6f3bc
      needs /\ /\ with {140.13}RELATION.139002
    | EVALUATE (cached result went bad), demand {140.13}RELATION.139002
    used by internal stage {139.14}SSAUtils::SSAHelper::custom_phi_node_dispred#fff SSAUtils::SSAHelper::phi_node_dispred#fff SSAUtils::SSAHelper::toString_dispred#ffff SSAUtils::SSAHelper::ssaDefinitionReachesEndOfBB_dispred#ffff SSAUtils::SSAHelper#class#f SSAUtils::SSAHelper::getAUse_dispred#ffff SSAUtils::SSAHelper#f SSAUtils::SSAHelper::ssa_defn_dispred#fffff with {139.14}RELATION.139002
    used by internal stage {140.13}SSAUtils::SSAHelper::toString_dispred#ffff SSAUtils::SSAHelper::ssaDefinitionReachesEndOfBB_dispred#ffff SSAUtils::SSAHelper::custom_phi_node_dispred#fff SSAUtils::SSAHelper::phi_node_dispred#fff SSAUtils::SSAHelper::ssa_defn_dispred#fffff SSAUtils::SSAHelper#class#f SSAUtils::SSAHelper::getAUse_dispred#ffff SSAUtils::SSAHelper#f with {140.13}RELATION.140002
    used by evaluator {139}FlowVar::FlowVar::toString_dispred#ff/2@e9b0c9 with {139.16}RELATION.139004
```

The query `{140}` that's the requester noted in the demand structure is `IncorrectPointerScaling.ql`, whose evaluation completed immediately before the exception was thrown.
