### ISSUE TITLE
C# System.IO.File unavailable

### ISSUE THREAD

**Issue by dittyroma** [github/codeql#6026]
Build seems to fail for a C# program that accesses the file system. Is there any way to get this working? Thank you!

I'm trying to query C# file system access, but the program build fails. I've put up a demonstration here. `src/experimental/Test/Test.ql` finds all `SystemIOFileClass` method calls. `test/experimental/Test/CreateFile.cs` is [this Microsoft example](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.create?view=net-5.0#System_IO_File_Create_System_String_).

https://github.com/dittyroma/codeql/tree/csharp-fs

This command reproduces on my system. I'm running on Linux.

```sh
$ codeql test run "/home/user/codeql/sft/codeql-repo/csharp/ql/test/experimental/Test" --show-extractor-output
```

I think the important error message is this. A `File.Create()` call hits this error.

```
error CS0103: The name 'File' does not exist in the current context
```

The `System.IO.File` class doesn't seem to be available. I see the compiler command toward the bottom. It doesn't include an IO DLL.

```
[ERROR] Spawned process exited abnormally (code 1; tried to run: [/home/user/codeql/sft/codeql/csharp/tools/linux64/Semmle.Extraction.CSharp.Driver, -unsafe, -target:library, /noconfig, /r:System.Private.CoreLib.dll, /r:System.dll, /r:System.Core.dll, /r:System.Runtime.dll, /r:System.Console.dll, --console, --verbosity, 2, CreateFile.cs])
```

In the CLI install there are many DLLs under `csharp/tools/linux64`. `System.IO.FileSystem.dll` might be the one. But I'm not sure how to get the build using it.

The full output.

```
Executing 1 tests in 1 directories.
Extracting test database in /home/user/codeql/sft/codeql-repo/csharp/ql/test/experimental/Test.
[2021-06-06 15:41:31] [build-err] Error:   Compilation error: /home/user/codeql/sft/codeql-repo/csharp/ql/test/experimental/Test/CreateFile.cs(14,36): error CS0103: The name 'File' does not exist in the current context
[2021-06-06 15:41:31] [build-err] Error:   Compilation error: /home/user/codeql/sft/codeql-repo/csharp/ql/test/experimental/Test/CreateFile.cs(22,38): error CS0103: The name 'File' does not exist in the current context
[2021-06-06 15:41:32] [build-err] Error:   Failed to determine type in fs = File.Create(path) at /home/user/codeql/sft/codeql-repo/csharp/ql/test/experimental/Test/CreateFile.cs: (13,30)-(13,52)    at Semmle.Extraction.Context.ReportError(InternalError error) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction/Context.cs:line 387
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.Context.ModelError(SyntaxNode node, String msg) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction/Context.cs:line 399
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.ExpressionNodeInfo.get_Type() in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/ExpressionNodeInfo.cs:line 67
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expression..ctor(IExpressionInfo info, Boolean shouldPopulate) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expression.cs:line 25
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expression`1..ctor(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expression`1.cs:line 13
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expressions.Invocation..ctor(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Invocation.cs:line 14
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expressions.Invocation.Create(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Invocation.cs:line 21
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expressions.Factory.Create(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Factory.cs:line 56
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expressions.ImplicitCast..ctor(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/ImplicitCast.cs:line 17
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expressions.ImplicitCast.Create(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/ImplicitCast.cs:line 83
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expression.CreateFromNode(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expression.cs:line 104
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expression.Create(Context cx, ExpressionSyntax node, IExpressionParentEntity parent, Int32 child) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expression.cs:line 102
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expressions.VariableDeclaration.<>c__DisplayClass9_0.<CreateDeclarator>b__0() in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/VariableDeclaration.cs:line 178
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.Context.Try(SyntaxNode node, ISymbol symbol, Action a) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction/Context.cs:line 432
[2021-06-06 15:41:32] [build-err] Error:   Failed to determine type in sr = File.OpenText(path) at /home/user/codeql/sft/codeql-repo/csharp/ql/test/experimental/Test/CreateFile.cs: (21,32)-(21,56)    at Semmle.Extraction.Context.ReportError(InternalError error) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction/Context.cs:line 387
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.Context.ModelError(SyntaxNode node, String msg) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction/Context.cs:line 399
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.ExpressionNodeInfo.get_Type() in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/ExpressionNodeInfo.cs:line 67
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expression..ctor(IExpressionInfo info, Boolean shouldPopulate) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expression.cs:line 25
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expression`1..ctor(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expression`1.cs:line 13
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expressions.Invocation..ctor(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Invocation.cs:line 14
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expressions.Invocation.Create(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Invocation.cs:line 21
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expressions.Factory.Create(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/Factory.cs:line 56
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expressions.ImplicitCast..ctor(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/ImplicitCast.cs:line 17
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expressions.ImplicitCast.Create(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/ImplicitCast.cs:line 83
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expression.CreateFromNode(ExpressionNodeInfo info) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expression.cs:line 104
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expression.Create(Context cx, ExpressionSyntax node, IExpressionParentEntity parent, Int32 child) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expression.cs:line 102
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.CSharp.Entities.Expressions.VariableDeclaration.<>c__DisplayClass9_0.<CreateDeclarator>b__0() in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction.CSharp/Entities/Expressions/VariableDeclaration.cs:line 178
[2021-06-06 15:41:32] [build-err]    at Semmle.Extraction.Context.Try(SyntaxNode node, ISymbol symbol, Action a) in /home/runner/work/semmle-code/semmle-code/ql/csharp/extractor/Semmle.Extraction/Context.cs:line 432
[2021-06-06 15:41:34] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/home/user/codeql/sft/codeql/csharp/tools/linux64/Semmle.Extraction.CSharp.Driver, -unsafe, -target:library, /noconfig, /r:System.Private.CoreLib.dll, /r:System.dll, /r:System.Core.dll, /r:System.Runtime.dll, /r:System.Console.dll, --console, --verbosity, 2, CreateFile.cs])
Could not extract a dataset in /home/user/codeql/sft/codeql-repo/csharp/ql/test/experimental/Test: Extraction command /home/user/codeql/sft/codeql/csharp/tools/linux64/Semmle.Extraction.CSharp.Driver failed with status 1.
Extraction command /home/user/codeql/sft/codeql/csharp/tools/linux64/Semmle.Extraction.CSharp.Driver failed with status 1.
[1/1] FAILED(EXTRACTION) /home/user/codeql/sft/codeql-repo/csharp/ql/test/experimental/Test/Test.qlref
Compiling queries in /home/user/codeql/sft/codeql-repo/csharp/ql/test/experimental/Test.
0 tests passed; 1 tests failed:
  FAILED: /home/user/codeql/sft/codeql-repo/csharp/ql/test/experimental/Test/Test.qlref
```

**Comment by tamasvajk** [comment]
Could you please try adding `/r:System.IO.FileSystem.dll` to the `// semmle-extractor-options` in your test input and see if this fixes your issue? You can find the some usages in other tests, such as [`/csharp/ql/test/library-tests/async/async.cs`](https://github.com/github/codeql/blob/b55526aa58a5b500fe5d1be2c7edd09075711d09/csharp/ql/test/library-tests/async/async.cs).

**Comment by dittyroma** [comment]
That did it! Thanks for the fast reply!
