### ISSUE TITLE
Internal error. (codeQL.runQueries)

### ISSUE THREAD

**Issue by phant0ms** [github/codeql#7620]
when run multi query ql file  wilt `CodeQL: Run Queries in Selected File`  in vscode right meun

a error was occurred

```
Internal error. (codeQL.runQueries)
Error: Internal error.
	at handleResponse (c:\Users\admin\.vscode\extensions\github.vscode-codeql-1.5.9\node_modules\vscode-jsonrpc\lib\main.js:449:48)
	at processMessageQueue (c:\Users\admin\.vscode\extensions\github.vscode-codeql-1.5.9\node_modules\vscode-jsonrpc\lib\main.js:276:17)
	at Immediate.<anonymous> (c:\Users\admin\.vscode\extensions\github.vscode-codeql-1.5.9\node_modules\vscode-jsonrpc\lib\main.js:260:13)
	at processImmediate (internal/timers.js:461:21)
Resolving tests using CodeQL CLI: resolve tests --strict-test-discovery -v --log-to-stderr --format json e:\codeql\codeql-repo...
CLI command succeeded.
```

```
CodeQL extension version: 1.5.9 
CodeQL CLI version: 2.7.3 
Platform: win32 x64
```

**Comment by tausbn** [comment]
Thank you for your report. I have not been able to recreate this error, and therefore I would like to know a bit more about the circumstances under which this happens.

Can you tell us which database (assuming it was one from LGTM.com) you were using, and which queries (assuming they were part of the standard CodeQL queries)?
