### ISSUE TITLE
 Spawned process exited abnormally 

### ISSUE THREAD

**Issue by himay1** [github/codeql#7711]
A fatal error occurred: Exit status 1 from command: [C:\codeql-home\codeql-cli\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, C:\codeql-home\codeql-cli\java\tools\autobuild.cmd]

**Comment by smowton** [comment]
Could you post the rest of the log so we can see what might have caused this?

**Comment by djthornton1212** [comment]
@smowton One of my developers is running into the same error, except mine is with JavaScript.

The application is a javascript/electron application and doesn't need to build.

## System
```
Node: 16
GitHub Hosted Runner: ubuntu-latest
```

## Error
```
[2022-05-03 14:38:32] [build-stderr] Exception while extracting /home/runner/work/endpoint/endpoint/js/opencv.js.
  [2022-05-03 14:38:32] [build-stderr] java.lang.OutOfMemoryError: Java heap space
  [2022-05-03 14:38:32] [build-stderr] 	at java.base/java.util.HashMap.resize(Unknown Source)
  [2022-05-03 14:38:32] [build-stderr] 	at java.base/java.util.HashMap.putVal(Unknown Source)
  [2022-05-03 14:38:32] [build-stderr] 	at java.base/java.util.HashMap.put(Unknown Source)
  [2022-05-03 14:38:32] [build-stderr] 	at java.base/java.util.HashSet.add(Unknown Source)
  [2022-05-03 14:38:32] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitLocationsDefault(LocationManager.java:156)
  [2022-05-03 14:38:32] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitFileLocation(LocationManager.java:146)
  [2022-05-03 14:38:32] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitSnippetLocation(LocationManager.java:141)
  [2022-05-03 14:38:32] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitNodeLocation(LocationManager.java:126)
  [2022-05-03 14:38:32] [build-stderr] 	at com.semmle.js.extractor.LexicalExtractor.extractTokens(LexicalExtractor.java:166)
  [2022-05-03 14:38:32] [build-stderr] 	at com.semmle.js.extractor.JSExtractor.extract(JSExtractor.java:113)
  [2022-05-03 14:38:32] [build-stderr] 	at com.semmle.js.extractor.JSExtractor.extract(JSExtractor.java:59)
  [2022-05-03 14:38:32] [build-stderr] 	at com.semmle.js.extractor.ScriptExtractor.extract(ScriptExtractor.java:85)
  [2022-05-03 14:38:32] [build-stderr] 	at com.semmle.js.extractor.FileExtractor.extractContents(FileExtractor.java:545)
  [2022-05-03 14:38:32] [build-stderr] 	at com.semmle.js.extractor.FileExtractor.extract(FileExtractor.java:452)
  [2022-05-03 14:38:32] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.doExtract(AutoBuild.java:1122)
  [2022-05-03 14:38:32] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.lambda$extract$8(AutoBuild.java:1106)
  [2022-05-03 14:38:32] [build-stderr] 	at com.semmle.js.extractor.AutoBuild$$Lambda$29/0x00000008000d4950.run(Unknown Source)
  [2022-05-03 14:38:32] [build-stderr] 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
  [2022-05-03 14:38:32] [build-stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  [2022-05-03 14:38:32] [build-stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  [2022-05-03 14:38:32] [build-stderr] 	at java.base/java.lang.Thread.run(Unknown Source)
  Error: 5-03 14:38:32] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh])
  A fatal error occurred: Exit status 1 from command: [/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh]
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/codeql' failed with exit code 2
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/codeql' failed with exit code 2
      at toolrunnerErrorCatcher (/home/runner/work/_actions/github/codeql-action/v1/lib/toolrunner-error-catcher.js:86:19)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Object.extractScannedLanguage (/home/runner/work/_actions/github/codeql-action/v1/lib/codeql.js:519:13)
      at async createdDBForScannedLanguages (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze.js:79:13)
      at async finalizeDatabaseCreation (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze.js:96:5)
      at async runFinalize (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze.js:259:5)
      at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze-action.js:78:9)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze-action.js:212:9)
```

## Suspected Issue
I see the line:

```
 Error: 5-03 14:38:32] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh])
```

So, I'm wondering if it's failing on trying to build something that doesn't actually build. 

## Workflow snippet
```
steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16

      # Initializes CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Install
        run: npm ci --quiet --ignore-scripts

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
```

**Comment by djthornton1212** [comment]
So, I've just realized that this workflow is using `@v1`, so I'm updating it to `@v2` and adding Debugging. I'll post back with my findings.

**Comment by djthornton1212** [comment]
Here's the re-run with debug and `codeql-action@v2`. This hasn't helped me any, but instead confused me as there are calls to what look like java classes in the logs.

```
[2022-05-03 16:05:46] [build-stderr] Exception while extracting /home/runner/work/endpoint/endpoint/js/opencv.js.
  [2022-05-03 16:05:46] [build-stderr] java.lang.OutOfMemoryError: Java heap space
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.HashMap.resize(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.HashMap.putVal(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.HashMap.put(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.HashSet.add(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitLocationsDefault(LocationManager.java:156)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitFileLocation(LocationManager.java:146)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitSnippetLocation(LocationManager.java:141)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitNodeLocation(LocationManager.java:126)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LexicalExtractor.extractTokens(LexicalExtractor.java:166)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.JSExtractor.extract(JSExtractor.java:113)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.JSExtractor.extract(JSExtractor.java:59)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.ScriptExtractor.extract(ScriptExtractor.java:85)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.FileExtractor.extractContents(FileExtractor.java:545)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.FileExtractor.extract(FileExtractor.java:452)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.doExtract(AutoBuild.java:1122)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.lambda$extract$8(AutoBuild.java:1106)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.AutoBuild$$Lambda$29/0x00000008000d4950.run(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.lang.Thread.run(Unknown Source)
  Error: 5-03 16:05:46] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh])
  [2022-05-03 16:05:46] Exception caught at top level: Exit status 1 from command: [/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh]
                        com.semmle.cli2.database.DatabaseProcessCommandCommon.executeSubcommand(DatabaseProcessCommandCommon.java:215)
                        com.semmle.cli2.database.TraceCommandCommand.executeSubcommand(TraceCommandCommand.java:86)
                        com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:500)
                        com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:205)
                        com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:214)
                        com.semmle.cli2.CodeQL.main(CodeQL.java:98)
  ::endgroup::
##[debug]Node Action run completed with exit code 1
##[debug]CODEQL_ACTION_RUN_MODE='Action'
##[debug]CODEQL_ACTION_VERSION='2.1.9'
##[debug]CODEQL_ACTION_FEATURE_SARIF_COMBINE='true'
##[debug]CODEQL_ACTION_FEATURE_WILL_UPLOAD='true'
##[debug]CODEQL_ACTION_FEATURE_MULTI_LANGUAGE='false'
##[debug]CODEQL_ACTION_FEATURE_SANDWICH='false'
##[debug]Finishing: Perform CodeQL Analysi
```

**Comment by smowton** [comment]
This has nothing in common with the original post -- I'll flag this to the JavaScript team to advise their recommended way of raising the extractor's memory limit.

**Comment by smowton** [comment]
Closing this issue as the OP never responded with any information that would enable diagnosing their problem; please take discussion of the JS OOM error to https://github.com/github/codeql-team/issues/945

**Comment by djthornton1212** [comment]
Yeah that link goes no where. I opened my own issue https://github.com/github/codeql/issues/9056.

**Comment by Maskhe** [comment]
I got the same error，is there any solution?
![image](https://github.com/github/codeql/assets/30264078/69d636b2-11c4-4c3d-b7fd-43d4733b1b19)
