### ISSUE TITLE
Creating too many QL classes generates an internal error when compiled

### ISSUE THREAD

**Issue by f52985** [github/codeql#7754]
Compiling the ql file with too many classes generates an internal error.

Here is the abbreviated ql file that reproduces the error:
```
//myQuery.ql
import cpp

class Class0 extends Expr {
  Class0() { this.toString() = "0" }
}
class Class1 extends Expr {
  Class1() { this.toString() = "1" }
}
class Class2 extends Expr {
  Class2() { this.toString() = "2" }
}
/*
...
Total 1000 classes
...
*/
class Class998 extends Expr {
  Class998() { this.toString() = "998" }
}
class Class999 extends Expr {
  Class999() { this.toString() = "999" }
}

select "Hello, world!"
```

and here is what I got when I tried to compile this ql file (`codeql query compile myQuery.ql`):
```
Oops! A fatal internal error occurred.
java.lang.ArrayIndexOutOfBoundsException: Index 283727587 out of bounds for length 0
	at com.semmle.bdd.SemmleBDDFactory.or(SemmleBDDFactory.java:859)
	at com.semmle.dil.proptypes.BoolExp$Bin.toBDD(BoolExp.java:146)
	at com.semmle.dil.proptypes.BoolExp$Bin.toBDD(BoolExp.java:137)
	at com.semmle.dil.proptypes.BoolExp.toZBDD(BoolExp.java:323)
	at com.semmle.dil.proptypes.QLPropTypeHierarchy.createHierarchy(QLPropTypeHierarchy.java:92)
	at com.semmle.dil.proptypes.QLPropTypeHierarchy.createHierarchy(QLPropTypeHierarchy.java:66)
	at com.semmle.dil.proptypes.PropTypeHierarchy.getPropTypeFactory(PropTypeHierarchy.java:35)
	at com.semmle.dil.proptypes.PropTypeHierarchy.top(PropTypeHierarchy.java:59)
	at com.semmle.dil.typeinference.TTC.top(TTC.java:116)
	at com.semmle.dil.typeinference.TTC.rename(TTC.java:127)
	at com.semmle.dil.absinthe.types.TypingFactory$Typing.rename(TypingFactory.java:575)
	at com.semmle.dil.absinthe.types.TypingFactory$Typing.rename(TypingFactory.java:594)
	at com.semmle.dil.absinthe.types.TypingFactory$Typing.rename(TypingFactory.java:234)
	at com.semmle.dil.absinthe.AbstractValue.expandSchema(AbstractValue.java:86)
	at com.semmle.dil.absinthe.util.PropagateValues.widenContext(PropagateValues.java:200)
	at com.semmle.dil.absinthe.util.PropagateValues.visitClause(PropagateValues.java:154)
	at com.semmle.dil.visit.DefaultVisitor.visit(DefaultVisitor.java:58)
	at com.semmle.dil.ast.Clause.accept(Clause.java:95)
	at com.semmle.dil.visit.DefaultVisitor.lambda$visit$1(DefaultVisitor.java:48)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.semmle.dil.visit.DefaultVisitor.visit(DefaultVisitor.java:48)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.semmle.dil.visit.DefaultVisitor.visit(DefaultVisitor.java:40)
	at com.semmle.dil.absinthe.util.PropagateValues.apply(PropagateValues.java:86)
	at com.semmle.dil.typeinference.Infer.propagate(Infer.java:51)
	at com.semmle.dil.typeinference.Infer.<init>(Infer.java:39)
	at com.semmle.dil.typeinference.Infer.inferAllTypes(Infer.java:43)
	at com.semmle.dil.compilation.CompilationPipeline.typeInferencePasses(CompilationPipeline.java:84)
	at com.semmle.frontend.compiler.QLCompileTarget$QLCompilationPipeline.typeInferencePasses(QLCompileTarget.java:86)
	at com.semmle.dil.compilation.CompilationPipeline.datalogPasses(CompilationPipeline.java:129)
	at com.semmle.dil.compilation.CompilationPipeline.runPasses(CompilationPipeline.java:187)
	at com.semmle.dil.compilation.CompilationPipeline.process(CompilationPipeline.java:204)
	at com.semmle.frontend.QLFrontend.analyse(QLFrontend.java:248)
	at com.semmle.frontend.QLFrontend.compile(QLFrontend.java:141)
	at com.semmle.cli2.ql.CompilationCommon.lambda$compile$1(CompilationCommon.java:245)
	at com.semmle.cli2.ql.CompilationCommon.compile(CompilationCommon.java:317)
	at com.semmle.cli2.ql.CompileCommand.lambda$executeSubcommand$0(CompileCommand.java:220)
	at com.semmle.cli2.ql.Paralleliser$1.lambda$next$0(Paralleliser.java:68)
	at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:217)
	at com.semmle.cli2.ql.Paralleliser.lambda$startMoreJobs$1(Paralleliser.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

I've found that this error does not occur when the number of classes is smaller, so I highly suspect that the main cause is actually related to the number of classes. (About 700~750 classes seems to be the maximum number of classes without an error, on my test environment).

I also found that the error happens on query console of lgtm.com: the compilation fails when there are too many classes, but succeeds when there are fewer classes.

Considering that cpp library (and/or any other libraries for different languages) already has thousands of classes, this might be a problem when trying to extend the library to support more features and requires fix.

Environment info:
CodeQL CLI version: 2.7.5
Java Version: openjdk 11.0.13 2021-10-19 LTS
OS: MacOS BigSur 11.6.2

**Comment by smowton** [comment]
Thanks for the report. Do you have a particular problem at the moment that stems from this limitation, or did you only find it in deliberate stress-testing? In general we're aware of this limitation (which applies to the shape of the type inheritance graph, not to an absolute number of classes defined), but if you're hitting it with some practical code then I'll ask if the relevant team can provide some advice to work around the issue.

**Comment by f52985** [comment]
In fact, I found this from the research experiment. More precisely, I tried to see if I can import both of cpp library and java library in one query file (after slightly modifying both of libraries), and since two libraries are already too large, importing both of them caused this problem.

I'm afraid there would be no workaround for the goal of 'fully merging two libraries' due to the fundamental limitation of current version of engine, but I'm happy to know if there would be a workaround for merging subsets from each library. (say, merge only dataflow module from each)

**Comment by alexet** [comment]
This error in particular is actually a bug and should be fixed in a future release (but we still will probably fail with very large type hierarchies for other reasons)

However it isn't really going to be possible to merge the two libraries even if the size wasn't an issue. The major problems are due to direct incompatibilities in the underlying data representation they expect.

**Comment by f52985** [comment]
Yes, I am aware of the issues when merging two libraries involving underlying database scheme. I have the rough idea of solving such the problem, and I was trying to check if really works.

Yet the size issue was the one that i could not resolve, and that's why I raised this issue.

I'm glad to see that it would be fixed in the later version. I'm looking forward to seeing it. Thanks for the confirmation!
