### ISSUE TITLE
Error reporting using vscode ast viewer

### ISSUE THREAD

**Issue by ernongxizhu** [github/codeql#8472]
I use QL statement to query normally, which indicates that there is no problem with the database, but an error will be reported when using ast view: cannot view the ast Please select a valid source file inside a CodeQL database. (codeQL.viewAst)
![image](https://user-images.githubusercontent.com/73651912/158731183-3d484a2d-9e83-49b0-a8a7-666ee9e5f155.png)

Error reporting details：
Cannot view the AST. Please select a valid source file inside a CodeQL database. (codeQL.viewAst)
Error: Cannot view the AST. Please select a valid source file inside a CodeQL database.
	at TemplatePrintAstProvider.getAst (c:\Users\xxx\.vscode\extensions\github.vscode-codeql-1.6.0\out\contextual\templateProvider.js:102:19)
	at CachedOperation.get (c:\Users\xxxx\.vscode\extensions\github.vscode-codeql-1.6.0\out\helpers.js:325:39)
	at TemplatePrintAstProvider.provideAst (c:\Users\xxxx\.vscode\extensions\github.vscode-codeql-1.6.0\out\contextual\templateProvider.js:92:32)
	at ctx.subscriptions.push.commandRunner_1.commandRunnerWithProgress.cancellable (c:\Users\xxxx\.vscode\extensions\github.vscode-codeql-1.6.0\out\extension.js:658:52)
	at c:\Users\xxxx\.vscode\extensions\github.vscode-codeql-1.6.0\out\commandRunner.js:38:16
	at S._withProgress (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:42843)
	at S.withProgress (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:42597)
	at Object.withProgress (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:40551)
	at withProgress (c:\Users\xxxx\.vscode\extensions\github.vscode-codeql-1.6.0\out\commandRunner.js:37:28)
	at c:\Users\xxxx\.vscode\extensions\github.vscode-codeql-1.6.0\out\commandRunner.js:109:26
	at f._executeContributedCommand (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:30255)
	at f.$executeContributedCommand (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:30797)
	at n._doInvokeHandler (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13812)
	at n._invokeHandler (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13496)
	at n._receiveRequest (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:12158)
	at n._receiveOneMessage (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:10836)
	at d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:8945
	at d.invoke (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at w.fire (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
	at c.fire (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19017)
	at d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:34267
	at d.invoke (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at w.fire (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
	at c.fire (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19017)
	at s._receiveMessage (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23598)
	at d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21132
	at d.invoke (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at w.fire (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
	at w.acceptChunk (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15848)
	at d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14978
	at Socket.P (d:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:13790)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by hvitved** [comment]
Are you sure that the selected file is indeed inside a QL database? It needs to have a file path that looks something like `.../src.zip/.../file` and the file must be Read Only.

**Comment by ernongxizhu** [comment]
> 

thank you~ I solved the problem

**Comment by hyy19sec** [comment]
> > 
> 
> thank you~ I solved the problem谢谢~我解决了问题

how would you solve the problem？
i meet the same problem
