### ISSUE TITLE
CatastrophicError for `query compile --fast-compilation`: Primitive directionalBind has more than one unbound field

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql#8999]
### Version
CodeQL CLI v2.9.0

### Description
It appears `query compile` with `--fast-compilation` can fail with a `CatastrophicError`:
```
Oops! A fatal internal error occurred.
com.semmle.util.exception.CatastrophicError: Primitive directionalBind has more than one unbound field: [DataFlowImpl::TNodeEx#17aa0c36 this, DataFlowImpl::TNodeEx#17aa0c36 result]
        at com.semmle.inmemory.planner.translate.TermTranslator$Result.applyPrimitiveAsKnownColumnOp(TermTranslator.java:625)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.translatePrimitiveCall(TermTranslator.java:1377)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1180)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1065)
        at com.semmle.dil.ast.Call.accept(Call.java:180)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.translate(TermTranslator.java:1082)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1650)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1065)
        at com.semmle.dil.ast.And.accept(And.java:120)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.translate(TermTranslator.java:1082)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1161)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1065)
        at com.semmle.dil.ast.Exists.accept(Exists.java:154)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.translate(TermTranslator.java:1082)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1650)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1065)
        at com.semmle.dil.ast.And.accept(And.java:120)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.translate(TermTranslator.java:1082)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1161)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1065)
        at com.semmle.dil.ast.Exists.accept(Exists.java:154)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.translate(TermTranslator.java:1082)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1650)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1065)
        at com.semmle.dil.ast.And.accept(And.java:120)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.translate(TermTranslator.java:1082)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1161)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1065)
        at com.semmle.dil.ast.Exists.accept(Exists.java:154)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.translate(TermTranslator.java:1082)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1650)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1065)
        at com.semmle.dil.ast.And.accept(And.java:120)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.translate(TermTranslator.java:1082)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1107)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.visit(TermTranslator.java:1065)
        at com.semmle.dil.ast.Or.accept(Or.java:119)
        at com.semmle.inmemory.planner.translate.TermTranslator$Translator.translate(TermTranslator.java:1082)
        at com.semmle.inmemory.planner.translate.TermTranslator.process(TermTranslator.java:255)
        at com.semmle.inmemory.planner.translate.TermTranslator.translate(TermTranslator.java:250)
        at com.semmle.inmemory.planner.translate.ProgramTranslator.translateNonRecursiveClause(ProgramTranslator.java:226)
        at com.semmle.inmemory.planner.translate.ProgramTranslator.doit(ProgramTranslator.java:152)
        at com.semmle.inmemory.planner.translate.ProgramTranslator.translate(ProgramTranslator.java:107)
        at com.semmle.inmemory.planner.Compiler.optimiseAndCompileOneProgram(Compiler.java:275)
        at com.semmle.inmemory.planner.StageDirector.computeStagedProgram(StageDirector.java:104)
        at com.semmle.inmemory.QueryCompiler.prepareQuery(QueryCompiler.java:60)
        at com.semmle.inmemory.QueryCompiler.prepareQueryWithTimeout(QueryCompiler.java:107)
        at com.semmle.api.QLCompilerUtils.compilePipelineToRa(QLCompilerUtils.java:325)
        at com.semmle.cli2.ql.CompilationCommon.compile(CompilationCommon.java:328)
        at com.semmle.cli2.ql.CompileCommand.lambda$executeSubcommand$0(CompileCommand.java:228)
        at com.semmle.cli2.ql.Paralleliser$1.lambda$next$0(Paralleliser.java:68)
        at com.semmle.util.concurrent.FutureUtils.supplyCompose(FutureUtils.java:217)
        at com.semmle.cli2.ql.Paralleliser.lambda$startMoreJobs$1(Paralleliser.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

Regular compilation without `--fast-compilation` does not seem to be affected.
This might be a newly introduced issue because it looks like this did not occur with CodeQL CLI v2.8.5.

### Reproduction steps
1. Clone https://github.com/Marcono1234/codeql-java-queries, branch `codeql-issue-8999`
2. Run the following command
    ```
    codeql query compile --fast-compilation --search-path=codeql ./codeql-custom-queries-java/queries/likely-bugs/non-thread-safe-iteration-of-synchronized-collection.ql
    ```

**Comment by aeisenberg** [comment]
Thanks for the report. I will forward this to our compiler team.

**Comment by jbj** [comment]
Thank you for the report. We've found the cause of this problem and concluded that a fix will not be trivial. Unless I hear about compelling use cases of `--fast-compilation` that raise the priority of this issue, I'll categorise this issue as technical debt and aim to have it fixed before the end of 2022.

**Comment by Marcono1234** [comment]
Thanks for the update!

My usecase is to perform compilation of all queries during a GitHub workflow run to make sure there are no errors, and I used `--fast-compilation` to speed up the workflow run a bit. I will try regular compilation then instead; combined with the Cache Action it will probably also not be so bad. So for me this is not so important.

Out of curiosity, does this error indicate that there is an issue with my query, or that it is written in a suboptimal way?

**Comment by jbj** [comment]
> My usecase is to perform compilation of all queries during a GitHub workflow run to make sure there are no errors, and I used `--fast-compilation` to speed up the workflow run a bit.

It sounds like the `--check-only` option is what you want, rather than `--fast-compilation`.

> Out of curiosity, does this error indicate that there is an issue with my query, or that it is written in a suboptimal way?

No. In CodeQL, `CatastrophicError` is always an internal error.
