### ISSUE TITLE
Spawned process exited abnormally - autobuild.sh

### ISSUE THREAD

**Issue by djthornton1212** [github/codeql#9056]
## Issue
**Description of the issue**

When executing the codeql analysis step the step appears to get stuck and eventually errors with the following output.

```
Exception while extracting /home/runner/work/endpoint/endpoint/js/opencv.js.
  [2022-05-03 16:05:46] [build-stderr] java.lang.OutOfMemoryError: Java heap space
```
```
Error: 5-03 16:05:46] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh])
  A fatal error occurred: Exit status 1 from command: [/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh]
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/codeql' failed with exit code 2
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/codeql' failed with exit code 2
```

The application is a javascript/electron application and doesn't need to build.

## System
```
Node: 16
GitHub Hosted Runner: ubuntu-latest
```

## Workflow

```
steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16

      # Initializes CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Install
        run: npm ci --quiet --ignore-scripts

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
```

## Error

```
Run github/codeql-action/analyze@v2
  with:
    output: ../results
    upload: true
    cleanup-level: brutal
    add-snippets: false
    skip-queries: false
    checkout_path: /home/runner/work/endpoint/endpoint
    upload-database: true
    wait-for-processing: true
    token: ***
    matrix: null
  env:
    CODEQL_ACTION_RUN_MODE: Action
    CODEQL_ACTION_VERSION: 2.1.9
    CODEQL_ACTION_FEATURE_SARIF_COMBINE: true
    CODEQL_ACTION_FEATURE_WILL_UPLOAD: true
    CODEQL_ACTION_ANALYSIS_KEY: .github/workflows/codeql-analysis.yml:analyze
    CODEQL_WORKFLOW_STARTED_AT: 2022-05-03T15:45:46.644Z
    CODEQL_ACTION_FEATURE_MULTI_LANGUAGE: false
    CODEQL_ACTION_FEATURE_SANDWICH: false
    CODEQL_RAM: 5922
    CODEQL_THREADS: 2
##[debug]Sending status report: {"workflow_run_id":2264846555,"workflow_name":"CodeQL","job_name":"analyze","analysis_key":".github/workflows/codeql-analysis.yml:analyze","commit_oid":"7a48ab830d271[32](https://github.com/company/endpoint/runs/6276172209?check_suite_focus=true#step:6:32)4cebe63749035894f877f419d","ref":"refs/pull/8/merge","action_name":"finish","action_ref":"v2","action_oid":"unknown","started_at":"2022-05-03T15:45:46.644Z","action_started_at":"2022-05-03T15:46:07.615Z","status":"starting","runner_os":"Linux","action_version":"2.1.9","matrix_vars":"null","runner_arch":"X64"}
##[debug]Loaded config:
##[debug]{"languages":["javascript"],"queries":{"javascript":{"builtin":["/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/AngularJS/DisablingSce.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/AngularJS/DoubleCompilation.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/AngularJS/InsecureUrlWhitelist.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/DOM/TargetBlank.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Electron/AllowRunningInsecureContent.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Electron/DisablingWebSecurity.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Performance/PolynomialReDoS.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Performance/ReDoS.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/RegExp/IdentityReplacement.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-020/IncompleteHostnameRegExp.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-020/IncompleteUrlSchemeCheck.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-020/IncompleteUrlSubstringSanitization.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-020/IncorrectSuffixCheck.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-020/UselessRegExpCharacterEscape.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-022/TaintedPath.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-022/ZipSlip.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-073/TemplateObjectInjection.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-078/CommandInjection.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-078/ShellCommandInjectionFromEnvironment.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-078/UnsafeShellCommandConstruction.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-078/UselessUseOfCat.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-079/ExceptionXss.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-079/ReflectedXss.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-079/StoredXss.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-079/UnsafeHtmlConstruction.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-079/UnsafeJQueryPlugin.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-079/Xss.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-079/XssThroughDom.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-089/SqlInjection.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-094/CodeInjection.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-094/ImproperCodeSanitization.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-094/UnsafeDynamicMethodAccess.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-1004/ClientExposedCookie.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-116/BadTagFilter.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-116/DoubleEscaping.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-116/IncompleteHtmlAttributeSanitization.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-116/IncompleteMultiCharacterSanitization.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-116/IncompleteSanitization.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-116/UnsafeHtmlExpansion.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-134/TaintedFormatString.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-200/PrivateFileExposure.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-201/PostMessageStar.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-209/StackTraceExposure.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-295/DisablingCertificateValidation.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-300/InsecureDependencyResolution.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-312/BuildArtifactLeak.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-312/CleartextLogging.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-312/CleartextStorage.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-326/InsufficientKeySize.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-327/BadRandomness.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-327/BrokenCryptoAlgorithm.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-[33](https://github.com/company/endpoint/runs/6276172209?check_suite_focus=true#step:6:33)8/InsecureRandomness.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-[34](https://github.com/company/endpoint/runs/6276172209?check_suite_focus=true#step:6:34)6/CorsMisconfigurationForCredentials.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-347/MissingJWTKeyVerification.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-[35](https://github.com/company/endpoint/runs/6276172209?check_suite_focus=true#step:6:35)2/MissingCsrfMiddleware.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220[40](https://github.com/company/endpoint/runs/6276172209?check_suite_focus=true#step:6:40)1/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-400/DeepObjectResourceExhaustion.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-502/UnsafeDeserialization.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-598/SensitiveGetQuery.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-601/ClientSideUrlRedirect.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-601/ServerSideUrlRedirect.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-611/Xxe.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-614/ClearTextCookie.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-640/HostHeaderPoisoningInEmailGeneration.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-6[43](https://github.com/company/endpoint/runs/6276172209?check_suite_focus=true#step:6:43)/XpathInjection.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-730/RegExpInjection.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-730/ServerCrash.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-754/UnvalidatedDynamicMethodCall.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-770/MissingRateLimiting.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-776/XmlBomb.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-798/HardcodedCredentials.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-829/InsecureDownload.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-830/FunctionalityFromUntrustedSource.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-834/LoopBoundInjection.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-843/TypeConfusionThroughParameterTampering.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-915/PrototypePollutingAssignment.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-915/PrototypePollutingFunction.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-915/PrototypePollutingMergeCall.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-916/InsufficientPasswordHash.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Security/CWE-918/RequestForgery.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Diagnostics/ExtractionErrors.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Diagnostics/SuccessfullyExtractedFiles.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Summary/LinesOfCode.ql","/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/qlpacks/codeql/javascript-queries/0.0.14/Summary/LinesOfUserCode.ql"],"custom":[]}},"pathsIgnore":[],"paths":[],"packs":{},"originalUserInput":{},"tempDir":"/home/runner/work/_temp","toolCacheDir":"/opt/hostedtoolcache","codeQLCmd":"/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/codeql","gitHubVersion":{"type":0},"dbLocation":"/home/runner/work/_temp/codeql_databases","debugMode":false,"debugArtifactName":"debug-artifacts","debugDatabaseName":"db","injectedMlQueries":false}
/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/codeql version --format=terse
2.8.5
(node:1791) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
::group::Extracting javascript
Extracting javascript
  /opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/codeql database trace-command /home/runner/work/_temp/codeql_databases/javascript -- /opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh
  Running command in /home/runner/work/endpoint/endpoint: [/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh]
  [2022-05-03 15:[46](https://github.com/company/endpoint/runs/6276172209?check_suite_focus=true#step:6:46):10] [build-stdout] Parallel extraction with 2 threads.

... a lot of extractions ...

[2022-05-03 15:46:23] [build-stdout] Done extracting /opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/data/externs/nodejs/stream.js (84 ms)
  [2022-05-03 16:05:46] [build-stderr] Exception while extracting /home/runner/work/endpoint/endpoint/js/opencv.js.
  [2022-05-03 16:05:46] [build-stderr] java.lang.OutOfMemoryError: Java heap space
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.HashMap.resize(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.HashMap.putVal(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.HashMap.put(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.HashSet.add(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitLocationsDefault(LocationManager.java:156)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitFileLocation(LocationManager.java:146)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitSnippetLocation(LocationManager.java:141)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitNodeLocation(LocationManager.java:126)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LexicalExtractor.extractTokens(LexicalExtractor.java:166)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.JSExtractor.extract(JSExtractor.java:113)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.JSExtractor.extract(JSExtractor.java:59)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.ScriptExtractor.extract(ScriptExtractor.java:85)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.FileExtractor.extractContents(FileExtractor.java:545)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.FileExtractor.extract(FileExtractor.java:452)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.doExtract(AutoBuild.java:1122)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.lambda$extract$8(AutoBuild.java:1106)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.AutoBuild$$Lambda$29/0x00000008000d4950.run(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.lang.Thread.run(Unknown Source)
  Error: 5-03 16:05:46] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh])
  A fatal error occurred: Exit status 1 from command: [/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh]
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/codeql' failed with exit code 2
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/codeql' failed with exit code 2
      at toolrunnerErrorCatcher (/home/runner/work/_actions/github/codeql-action/v2/lib/toolrunner-error-catcher.js:86:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.extractScannedLanguage (/home/runner/work/_actions/github/codeql-action/v2/lib/codeql.js:519:13)
      at async createdDBForScannedLanguages (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:79:13)
      at async finalizeDatabaseCreation (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:96:5)
      at async runFinalize (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:259:5)
      at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:78:9)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:212:9)
  ##[debug]Sending status report: {"workflow_run_id":2264846555,"workflow_name":"CodeQL","job_name":"analyze","analysis_key":".github/workflows/codeql-analysis.yml:analyze","commit_oid":"7a48ab830d271324cebe6[374](https://github.com/company/endpoint/runs/6276172209?check_suite_focus=true#step:6:374)9035894f877f419d","ref":"refs/pull/8/merge","action_name":"finish","action_ref":"v2","action_oid":"unknown","started_at":"2022-05-03T15:45:46.644Z","action_started_at":"2022-05-03T15:46:07.615Z","status":"failure","runner_os":"Linux","action_version":"2.1.9","cause":"The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/codeql' failed with exit code 2","exception":"Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/codeql' failed with exit code 2\n    at toolrunnerErrorCatcher (/home/runner/work/_actions/github/codeql-action/v2/lib/toolrunner-error-catcher.js:86:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.extractScannedLanguage (/home/runner/work/_actions/github/codeql-action/v2/lib/codeql.js:519:13)\n    at async createdDBForScannedLanguages (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:79:13)\n    at async finalizeDatabaseCreation (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:96:5)\n    at async runFinalize (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze.js:259:5)\n    at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:78:9)\n    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/analyze-action.js:212:9)","completed_at":"2022-05-03T16:05:46.170Z","matrix_vars":"null","runner_arch":"X64","codeql_version":"2.8.5","ml_powered_javascript_queries":"false"}
```

## Debug Mode
```
Debug mode is on. Printing CodeQL debug logs...
  ::group::CodeQL Debug Logs - javascript - database-trace-command-20220503.154609.871.log
CodeQL Debug Logs - javascript - database-trace-command-20220503.154609.871.log
  [2022-05-03 15:46:09] This is codeql database trace-command /home/runner/work/_temp/codeql_databases/javascript -- /opt/hostedtoolcache/CodeQL/0.0.0-20220[401](https://github.com/company/endpoint/runs/6276172209?check_suite_focus=true#step:6:401)/x64/codeql/javascript/tools/autobuild.sh
  [2022-05-03 15:46:09] Log file was started late.
  [2022-05-03 15:46:09] [PROGRESS] database trace-command> Running command in /home/runner/work/endpoint/endpoint: [/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh]

... a lot of extractions ...

[2022-05-03 15:46:23] [build-stdout] Done extracting /opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/data/externs/nodejs/stream.js (84 ms)
  [2022-05-03 16:05:46] [build-stderr] Exception while extracting /home/runner/work/endpoint/endpoint/js/opencv.js.
  [2022-05-03 16:05:46] [build-stderr] java.lang.OutOfMemoryError: Java heap space
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.HashMap.resize(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.HashMap.putVal(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.HashMap.put(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.HashSet.add(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitLocationsDefault(LocationManager.java:156)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitFileLocation(LocationManager.java:146)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitSnippetLocation(LocationManager.java:141)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LocationManager.emitNodeLocation(LocationManager.java:126)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.LexicalExtractor.extractTokens(LexicalExtractor.java:166)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.JSExtractor.extract(JSExtractor.java:113)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.JSExtractor.extract(JSExtractor.java:59)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.ScriptExtractor.extract(ScriptExtractor.java:85)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.FileExtractor.extractContents(FileExtractor.java:545)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.FileExtractor.extract(FileExtractor.java:452)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.doExtract(AutoBuild.java:1122)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.AutoBuild.lambda$extract$8(AutoBuild.java:1106)
  [2022-05-03 16:05:46] [build-stderr] 	at com.semmle.js.extractor.AutoBuild$$Lambda$29/0x00000008000d4950.run(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  [2022-05-03 16:05:46] [build-stderr] 	at java.base/java.lang.Thread.run(Unknown Source)
  Error: 5-03 16:05:46] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh])
  [2022-05-03 16:05:46] Exception caught at top level: Exit status 1 from command: [/opt/hostedtoolcache/CodeQL/0.0.0-20220401/x64/codeql/javascript/tools/autobuild.sh]
                        com.semmle.cli2.database.DatabaseProcessCommandCommon.executeSubcommand(DatabaseProcessCommandCommon.java:215)
                        com.semmle.cli2.database.TraceCommandCommand.executeSubcommand(TraceCommandCommand.java:86)
                        com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:500)
                        com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:205)
                        com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:214)
                        com.semmle.cli2.CodeQL.main(CodeQL.java:98)
  ::endgroup::
##[debug]Node Action run completed with exit code 1
##[debug]CODEQL_ACTION_RUN_MODE='Action'
##[debug]CODEQL_ACTION_VERSION='2.1.9'
##[debug]CODEQL_ACTION_FEATURE_SARIF_COMBINE='true'
##[debug]CODEQL_ACTION_FEATURE_WILL_UPLOAD='true'
##[debug]CODEQL_ACTION_FEATURE_MULTI_LANGUAGE='false'
##[debug]CODEQL_ACTION_FEATURE_SANDWICH='false'
##[debug]Finishing: Perform CodeQL Analysis
```

**Comment by asgerf** [comment]
Hi 👋 

It is best to use the [paths-ignore](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#specifying-directories-to-scan) feature to exclude the file `opencv.js`. It would look something like this:
```yaml
paths-ignore:
  - '**/opencv.js'
```

In general, when a repository contains a huge JS file that is output of a compiler/bundler process, it is best to exclude it. I'm guessing `opencv.js` is from the OpenCV project, it which case it is the result of translating some C++ code to JS using Emscripten. This source code is unreadable and it wouldn't be helpful to get code scanning alerts in such files anyway.

**Comment by djthornton1212** [comment]
@asgerf That fixed it. Thank you very much for the help!
