### ISSUE TITLE
result abbreviation

### ISSUE THREAD

**Issue by lrecknagel** [github/codeql#9890]
Maybe I get something wrong but I cant help myself nor find any useful hints in existing issues or documentation regarding the following case:

* Taking for example a select like:

```codeql
import javascript

from Function fn, File f, Parameter p
where
  f.getAbsolutePath() = fn.getFile().getAbsolutePath()
  and p.getContainer() = fn
select
  fn.getAReturnedExpr(),
  fn.getAReturnedExpr().toString()
```

* The results are in most of the time abbreviated with three dots like: `something ... something`
* **Question**: is there any way, setting to expand the full string somehow in the results?

Any help is appreciated - thanks to all of you in advance and also to make all this amazing stuff happen!

**Comment by alexet** [comment]
in general `toString` is expected to return a short human readable string and also be easy to compute. For these reasons `toString` returns a short string that usually only shows 1 level of information. We also don't have the full source for objects in the database so the abbreviated object is the only option available. 

However things should also have `getLocation` that returns the location of the object. If it does have `getLocation` just clicking on the result in vscode should link you directly to the actual source code.

**Comment by intrigus-lgtm** [comment]
Hi, I once asked a similar question:
https://github.com/github/securitylab/discussions/53
Maybe this will help you.

**Comment by lrecknagel** [comment]
@alexet thanks for you explanation - I also see this possibility but its not very scalable for larger result sets imho.
@intrigus-lgtm thanks for pointing me there.

@alexet is there anything I can support to "fix" this issue as you pointed out in https://github.com/github/securitylab/discussions/53

**Comment by alexet** [comment]
So that problem is slightly different because it deals with an expression that is essentially an atomic value being truncated.

The general problem ends up being much harder. The main problem is the underlying codeql string representation which doesn't allow sharing between strings. As most of the time we only deal with the short strings (like inside identifiers) we want to tune the representation towards the actual uses. However if we were to have all the actual expressions between the language it would take `O(nestingDepth*programSize)` space. The evaluation model of codeql is bottom up so every predicate is evaluated in full so we are essentially required to compute all those strings. 

What is the actual use case for getting the full text? There is usually a better way than relying on the full text anyway.

**Comment by ydelvis** [comment]
Hi @lrecknagel, did you come up with a workaround for this?

@alexet , in my case I'm using CodeQL CLI and would like to fetch all parameters (full text) supplied to some filtered method calls for further analysis.

I came across this [solution ](https://stackoverflow.com/questions/76334385/how-do-i-display-full-string-in-a-codeql-exported-result) on StackOverflow, but I'm not sure where to re-install the javascript pack (step 5).  I have literally run `codeql pack install --force` in almost all directories containing a 'qlpack.yml' file but still run into the error below when I try to re-create the database:

> ...
[2025-02-02 02:18:29] [build-stderr]    at com.semmle.js.extractor.AutoBuild.extractSource(AutoBuild.java:751)
[2025-02-02 02:18:29] [build-stderr]    at com.semmle.js.extractor.AutoBuild.run(AutoBuild.java:464)
[2025-02-02 02:18:29] [build-stderr]    at com.semmle.js.extractor.AutoBuild.main(AutoBuild.java:1360)
[2025-02-02 02:18:29] [ERROR] Spawned process exited abnormally (code 1; tried to run: [C:\Users\Akwasi\codeql-home\codeql\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, C:\Users\Akwasi\codeql-home\codeql\javascript\tools\autobuild.cmd])
A fatal error occurred: Exit status 1 from command: [C:\Users\Akwasi\codeql-home\codeql\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, C:\Users\Akwasi\codeql-home\codeql\javascript\tools\autobuild.cmd]

I'd appreciate any help on this. Thanks!

**Comment by intrigus-lgtm** [comment]
> Hi @lrecknagel, did you come up with a workaround for this?
> 
> @alexet , in my case I'm using CodeQL CLI and would like to fetch all parameters (full text) supplied to some filtered method calls for further analysis.
> 
> I came across this [solution ](https://stackoverflow.com/questions/76334385/how-do-i-display-full-string-in-a-codeql-exported-result) on StackOverflow, but I'm not sure where to re-install the javascript pack (step 5). I have literally run `codeql pack install --force` in almost all directories containing a 'qlpack.yml' file but still run into the error below when I try to re-create the database:
> 
> > ...
> > [2025-02-02 02:18:29] [build-stderr]    at com.semmle.js.extractor.AutoBuild.extractSource(AutoBuild.java:751)
> > [2025-02-02 02:18:29] [build-stderr]    at com.semmle.js.extractor.AutoBuild.run(AutoBuild.java:464)
> > [2025-02-02 02:18:29] [build-stderr]    at com.semmle.js.extractor.AutoBuild.main(AutoBuild.java:1360)
> > [2025-02-02 02:18:29] [ERROR] Spawned process exited abnormally (code 1; tried to run: [C:\Users\Akwasi\codeql-home\codeql\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, C:\Users\Akwasi\codeql-home\codeql\javascript\tools\autobuild.cmd])
> > A fatal error occurred: Exit status 1 from command: [C:\Users\Akwasi\codeql-home\codeql\tools\win64\runner.exe, cmd.exe, /C, type, NUL, &&, C:\Users\Akwasi\codeql-home\codeql\javascript\tools\autobuild.cmd]
> 
> I'd appreciate any help on this. Thanks!

I'd recommend not trying to patch the CodeQL extractor.

Assuming you have the source code of the project nearby, you can output the query results as csv, which should include the location of the expressions.
You can then manually extract the full text of the expression using a helper script as there is currently no other way as far as I know.

For how to extract the location, there is this option for `database analyze` that might be helpful.
```
--csv-location-format=<csvLocationFormat>
                             The format in which to produce locations in CSV output. One of:
                               uri, line-column, offset-length. (Default: line-column)
```

**Comment by ydelvis** [comment]
Thanks for the input @intrigus-lgtm.  Manually inspecting each location wouldn't be suitable and scalable for my scenario.  That's why I need a way to get the full strings.

**Comment by intrigus-lgtm** [comment]
> Thanks for the input @intrigus-lgtm. Manually inspecting each location wouldn't be suitable and scalable for my scenario. That's why I need a way to get the full strings.

Apologies if my message was unclear, but you don't have to manually inspect each location.

You write a program that takes the csv results with location data and that then outputs the full string by using the location information and extracting the string from a provided source code.
