### ISSUE TITLE
codeql create database faile with java.lang.OutOfMemoryError for a C/C++ project

### ISSUE THREAD

**Issue by Securee** [github/codeql#9933]
hi all,
    I want to use codeql to analyze a C/C++ project，but it failed with the log as :
[2022-07-30 16:46:07] [ERROR] An exception occurred during TRAP import. The database may be partial.
                              java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
                              	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
                              	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
                              	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
                              	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
                              	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
                              	at java.base/java.lang.Thread.run(Unknown Source)
                              Caused by: java.lang.OutOfMemoryError: Java heap space
                              	at java.base/java.util.LinkedHashMap.newNode(Unknown Source)
                              	at java.base/java.util.HashMap.putVal(Unknown Source)
                              	at java.base/java.util.HashMap.put(Unknown Source)
                              	at java.base/java.util.HashSet.add(Unknown Source)
                              	at com.semmle.util.trap.dependencies.TextFile.load(TextFile.java:87)
                              	at com.semmle.util.trap.dependencies.TrapSet.<init>(TrapSet.java:59)
                              	at com.semmle.inmemory.trap.TRAPLinker.addTrapAndDependenciesToSet(TRAPLinker.java:442)
                              	at com.semmle.inmemory.trap.TRAPLinker.computeObjectToTrap(TRAPLinker.java:426)
                              	at com.semmle.inmemory.trap.TRAPLinker.getTasks(TRAPLinker.java:181)
                              	at com.semmle.inmemory.trap.TrapImporter.lambda$scanAndLink$3(TrapImporter.java:186)
                              	at com.semmle.inmemory.trap.TrapImporter$$Lambda$303/0x0000000800310000.apply(Unknown Source)
                              	at com.semmle.util.concurrent.FutureUtils.lambda$mapAsync$4(FutureUtils.java:120)
                              	at com.semmle.util.concurrent.FutureUtils$$Lambda$305/0x0000000800310698.get(Unknown Source)
                              	... 4 common frames omitted
[2022-07-30 16:46:07] Pausing evaluation to close the cache at sequence stamp o+3
[2022-07-30 16:46:07] The disk cache is freshly trimmed; leave it be.
[2022-07-30 16:46:07] Unpausing evaluation
[2022-07-30 16:46:07] Exception caught at top level: java.lang.RuntimeException: java.lang.OutOfMemoryError: Java heap space
                      com.semmle.util.exception.Exceptions.asUnchecked(Exceptions.java:103)
                      com.semmle.inmemory.trap.TrapImporter.run(TrapImporter.java:113)
                      com.semmle.cli2.ql.dataset.ImportCommand.executeSubcommand(ImportCommand.java:95)
                      com.semmle.cli2.picocli.PlumbingRunner.run(PlumbingRunner.java:110)
                      com.semmle.cli2.picocli.SubcommandCommon.runPlumbingInProcess(SubcommandCommon.java:162)
                      com.semmle.cli2.database.FinalizeCommand.doTrapImport(FinalizeCommand.java:187)
                      com.semmle.cli2.database.FinalizeCommand.finalizeOne(FinalizeCommand.java:148)
                      com.semmle.cli2.database.FinalizeCommand.executeSubcommand(FinalizeCommand.java:91)
                      com.semmle.cli2.picocli.PlumbingRunner.run(PlumbingRunner.java:110)
                      com.semmle.cli2.picocli.SubcommandCommon.runPlumbingInProcess(SubcommandCommon.java:162)
                      com.semmle.cli2.database.CreateCommand.executeSubcommand(CreateCommand.java:169)
                      com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:500)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:205)
                      com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:214)
                      com.semmle.cli2.CodeQL.main(CodeQL.java:98)
                      
                       ... caused by:
                      
                      java.lang.OutOfMemoryError: Java heap space
                      java.base/java.util.LinkedHashMap.newNode(Unknown Source)
                      java.base/java.util.HashMap.putVal(Unknown Source)
                      java.base/java.util.HashMap.put(Unknown Source)
                      java.base/java.util.HashSet.add(Unknown Source)
                      com.semmle.util.trap.dependencies.TextFile.load(TextFile.java:87)
                      com.semmle.util.trap.dependencies.TrapSet.<init>(TrapSet.java:59)
                      com.semmle.inmemory.trap.TRAPLinker.addTrapAndDependenciesToSet(TRAPLinker.java:442)
                      com.semmle.inmemory.trap.TRAPLinker.computeObjectToTrap(TRAPLinker.java:426)
                      com.semmle.inmemory.trap.TRAPLinker.getTasks(TRAPLinker.java:181)
                      com.semmle.inmemory.trap.TrapImporter.lambda$scanAndLink$3(TrapImporter.java:186)
                      com.semmle.inmemory.trap.TrapImporter$$Lambda$303/0x0000000800310000.apply(Unknown Source)
                      com.semmle.util.concurrent.FutureUtils.lambda$mapAsync$4(FutureUtils.java:120)
                      com.semmle.util.concurrent.FutureUtils$$Lambda$305/0x0000000800310698.get(Unknown Source)
                      java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
                      java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
                      java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
                      java.base/java.lang.Thread.run(Unknown Source)

and I have tried:
      1) export SEMMLE_JAVA_EXTRACTOR_JVM_ARGS='-Xmx8g -Xms1g'
      2) add Xmx to the command: codeql database create -J -Xmx8g --language=cpp ...
but all failed.
      so,is there any way to fix this issue?

**Comment by aibaars** [comment]
Have you tried the `--ram` flag of `codeql database create`.

**Comment by Securee** [comment]
> Have you tried the `--ram` flag of `codeql database create`.
> 
> ```
>  -M, --ram=<MB>             Use this much memory for the import operation, and
>                                pass it as a hint to any invoked build commands.
> ```

Thanks , it does work for me.
